### ISSUE TITLE
crashing during first time launch

### ISSUE THREAD

**Issue by bmm23** [pointfeev/CreamInstaller#1]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Gameloop.Vdf.VdfException: Incomplete VDF data.
   at Gameloop.Vdf.VdfSerializer.Deserialize(TextReader textReader)
   at Gameloop.Vdf.VdfConvert.Deserialize(TextReader reader, VdfSerializerSettings settings)
   at CreamInstaller.SelectForm.GetGamesFromLibraryDirectory(String libraryDirectory, List`1& games) in D:\Items\Development\CreamInstaller\CreamInstaller\SelectForm.cs:line 80
   at CreamInstaller.SelectForm.GetCreamApiApplicablePrograms(IProgress`1 progress) in D:\Items\Development\CreamInstaller\CreamInstaller\SelectForm.cs:line 116
   at CreamInstaller.SelectForm.<>c__DisplayClass9_0.<OnLoad>b__3() in D:\Items\Development\CreamInstaller\CreamInstaller\SelectForm.cs:line 286
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CreamInstaller.SelectForm.OnLoad() in D:\Items\Development\CreamInstaller\CreamInstaller\SelectForm.cs:line 286
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Private.CoreLib.dll
----------------------------------------
CreamInstaller
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/CreamInstaller.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.11.0
    Win32 Version: 5.0.1121.47402
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.11.0
    Win32 Version: 5.0.1121.47402
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.421.11614
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1121.47402
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.11.0
    Win32 Version: 5.0.1121.47402
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Diagnostics.Process.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.IO.Compression.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Collections.NonGeneric.dll
----------------------------------------
Onova
    Assembly Version: 2.6.2.0
    Win32 Version: 2.6.2.0
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Onova.dll
----------------------------------------
System.Net.Http
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.Primitives.dll
----------------------------------------
System.Net.Security
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.Security.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Text.Json
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Text.Json.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Collections.Concurrent.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.NetworkInformation.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.NameResolution.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Threading.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Collections.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Memory.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Text.RegularExpressions.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.IO.FileSystem.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Net.WebClient.dll
----------------------------------------
System.IO.Compression.ZipFile
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.IO.Compression.ZipFile.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Microsoft.Win32.Registry.dll
----------------------------------------
Gameloop.Vdf
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Gameloop.Vdf.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Linq.Expressions.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Private.CoreLib.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1121.47308
    CodeBase: file:///C:/Users/Brendan/AppData/Local/Temp/.net/CreamInstaller/3bfwtku2.n3s/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

The program (2.0) crashed during first time use. No functionality even after clicking continue

**Comment by pointfeev** [comment]
Should be fixed in v2.0.0.1! :)

If not then please do tell me, otherwise I'll close the issue in about a week or so. 👍

**Comment by bmm23** [comment]
excellent, that fixed it. Thanks for the quick fix, haven't had internet to test it until now

**Comment by bmm23** [comment]
excellent, that fixed it. Thanks for the quick fix, haven't had internet to test it until now
