### ISSUE TITLE
Binding of isaac repentance

### ISSUE THREAD

**Issue by Willytor** [pointfeev/CreamInstaller#10]
I own the binding of isaac  legitimately and its 2 earlier dlcs (afterbirth and afterbirth+) and i'm trying to use creaminstaller to get Repentance. Even after installing with creaminstaller when the game launches it's just afterbirth +. Could have something to do with the fact that it's from a shared steam library (so its technically not owned by me)

**Comment by pointfeev** [comment]
You likely need to download the DLC and put them in your game directory. Consult [this topic](https://cs.rin.ru/forum/viewtopic.php?f=10&t=65646).

**Comment by Willytor** [comment]
ty. works now
