### ISSUE TITLE
Subject: Issue with Cream API and Cities: Skylines after Recent Update

### ISSUE THREAD

**Issue by Mrcitiesskylines** [pointfeev/CreamInstaller#104]
Dear Cream API Developers,

I hope this message finds you well. I wanted to bring to your attention an issue that has arisen with the Cream API and its compatibility with Cities: Skylines.

Until the update released on May 12th, I had been enjoying a seamless experience using Cities: Skylines in conjunction with the Cream API. The API allowed me to utilize the game's DLC features successfully, enhancing my gameplay. However, since this latest update, I have encountered a persistent problem: the game crashes consistently when attempting to load a map.

I have verified the game files through Steam, ensured compatibility between the Cream API version and my current Cities: Skylines version, and removed any conflicting mods. Despite these efforts, the issue persists, indicating a possible compatibility conflict or a need for an update to the Cream API.

I kindly request your assistance in addressing this matter. Could you please investigate the issue and release an update or provide any guidance that would help resolve this compatibility problem? I understand that development and debugging can be time-consuming processes, and I appreciate your efforts in maintaining the Cream API and supporting the Cities: Skylines modding community.

If there is any additional information I can provide, such as error logs or screenshots, please let me know, and I will be happy to assist. I look forward to your response and a potential resolution to this issue.

Thank you for your attention and dedication to improving the Cream API. Your efforts are highly valued by the Cities: Skylines community.

**Comment by Mrcitiesskylines** [comment]
it is something to do with ur code cause 2 weeks before it was working fine but after cities skylines updated on 12th may it crashes when loading map

**Comment by pointfeev** [comment]
After a game update you may need to reinstall the unlocker with the program AND/OR update the DLCs in the game folder.

**Comment by Mrcitiesskylines** [comment]
I have re-installed the API many times and the game but it didn't work I also changes the settings to just install smoke. api and not vision API but it didn't work I suggest u update ur code cause on the 23rd they are adding 3 new dlcs which will break ur API

**Comment by Mrcitiesskylines** [comment]
i can provide u wat has been changed in the past update if u wish

**Comment by pointfeev** [comment]
Pardon my rudeness, but there is plenty of information I've given you in this issue and in the README to solve your problem, so please, less typing, more reading.
