### ISSUE TITLE
Heroic Game Launcher Support

### ISSUE THREAD

**Issue by animetrom** [pointfeev/CreamInstaller#106]
Please add support for Heroic Game Launcher. I would love to use it instead of the original Epic Games launcher, but the games are not recognized in CreamInstaller, only installed by the official epic launcher.

**Comment by pointfeev** [comment]
I'll definitely look into it and see if it's possible :)

**Comment by pointfeev** [comment]
Support for Epic games installed via the Heroic Games Launcher will be included in v4.9.0!

**Comment by animetrom** [comment]
When installing Heroic games like Barony there was no detection by CreamInstaller. Did I do something wrong maybe?

**Comment by pointfeev** [comment]
I installed Heroic x64, downloaded Dungeons 3, making sure the manifest from the Epic launcher was deleted so it wasn't reading it from Epic Games Launcher, and it read it from the Heroic library file fine for me. It has to actually be an Epic game, so make sure you aren't trying for a GOG game and realize that it will show up under the Epic platform.

**Comment by pointfeev** [comment]
I've just tested it again and it seems to work exactly how it's supposed to, please do let me know if I'm missing something. You can take a look at how I do it and see if it lines up with your installation [here](https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Platforms/Epic/Heroic/HeroicLibrary.cs).

**Comment by animetrom** [comment]
Could you help me again, please? I don't know what I'm doing wrong.
Heroic installed, epic games uninstalled. Games are installed in D:\Games\Heroic.
File heroic\store_cache\legendary_library.json, exists but does not detect.

Print of the installed game: https://i.imgur.com/e1t8Ni8.png
Print of the file your code pulls: https://i.imgur.com/rhWjUuK.png

Could you help me understand, what am I doing wrong, please?
