### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Jargonnut** [pointfeev/CreamInstaller#112]
Everytime I try to download CreamInstaller, I get this:

Secure Connection Failed

An error occurred during a connection to codeload.github.com. PR_CONNECT_RESET_ERROR

Error code: PR_CONNECT_RESET_ERROR

any ideas ?
Thanks
Jay

**Comment by pointfeev** [comment]
Is this while updating via the program dialog or while literally downloading from releases? If it's the latter then that's entirely out of my control, and it's on GitHub's side. I've never seen such an error myself so you're better off googling it.
