### ISSUE TITLE
dlc not unlocking with errors (screenshots provided)

### ISSUE THREAD

**Issue by ronhin375** [pointfeev/CreamInstaller#114]
![Screenshot (1)](https://github.com/pointfeev/CreamInstaller/assets/95559036/8518b401-ef34-44c3-89e0-9f3808a85fc9)
![Screenshot (4)](https://github.com/pointfeev/CreamInstaller/assets/95559036/29c50979-bf63-47e0-9300-6b92e5091891)
![Screenshot (5)](https://github.com/pointfeev/CreamInstaller/assets/95559036/7754c35c-cf4a-4a56-8a53-6b6dc232761a)

**Comment by pointfeev** [comment]
Should be fixed in v4.9.1!
