### ISSUE TITLE
4.9.2 - all steam apps are doubled

### ISSUE THREAD

**Issue by dimkKy** [pointfeev/CreamInstaller#115]
###### Describe the bug and/or provide an image of the exception dialog box:

It also does not work (tested with Stellaris - all logs are green but no (and I mean it, game does not see DLCs at all) while everything is fine using 4.8.1

https://github.com/pointfeev/CreamInstaller/assets/76184420/d38a942f-9a31-44bc-b02c-07a8e250e63b

**Comment by pointfeev** [comment]
I think I may have figured out what's causing this, I should have it fixed in v4.9.3 later today!

**Comment by pointfeev** [comment]
Should be fixed in v4.9.3
