### ISSUE TITLE
Checklist button label text is squeezed.

### ISSUE THREAD

**Issue by pomodori92** [pointfeev/CreamInstaller#116]
###### Describe the bug and/or provide an image of the exception dialog box:

As you can see in the attached image below, the checklist button label text is squeezed.

OS: Windows 10 22H2
CreamInstaller version: 4.9.2

Thank you for your work! I appreciate it so much!

![fBXHtJD9WU](https://github.com/pointfeev/CreamInstaller/assets/45762339/249b48f5-411e-4dd7-8728-e6dbd6384a2d)

**Comment by pointfeev** [comment]
Should be fixed in v4.9.7!
