### ISSUE TITLE
Exception caused by foreign characters in system name

### ISSUE THREAD

**Issue by bootmgfw** [pointfeev/CreamInstaller#12]
![Screenshot_1](https://user-images.githubusercontent.com/86889160/158292238-4ca88f02-75a8-4d92-8be3-5b8eef2b6ce8.png)
![Screenshot_2](https://user-images.githubusercontent.com/86889160/158292240-68045303-6994-4af0-8712-b0ae1df79910.png)

**Comment by bootmgfw** [comment]
Note: This problem was not present in build 2.4.3.1, not sure when this problem starts.

**Comment by pointfeev** [comment]
Shucks, I actually feared that may be an issue when I decided to use system name there, I should have it fixed in a bit! :)

**Comment by pointfeev** [comment]
Fixed in v3.2.3.2! :)

**Comment by bootmgfw** [comment]
<3
