### ISSUE TITLE
SafeIO Unauthorized Access Exception

### ISSUE THREAD

**Issue by JakeGamerOP** [pointfeev/CreamInstaller#120]
I was download a DLC (warhamer40k) but when 
![Captura de pantalla 2023-06-06 22 27 15](https://github.com/pointfeev/CreamInstaller/assets/135792762/405ddd22-d3d7-41c7-ad5b-f7cf159e8976)
I tried i receive this message

**Comment by pointfeev** [comment]
Your game was likely open whilst you were installing; I'll see if I can't add more detailed messages for unauthorized access in the future.

**Comment by JakeGamerOP** [comment]
I closed steam and after trying several times it seems only 2 dlc could be unlocked
![imagen_2023-06-09_004112611](https://github.com/pointfeev/CreamInstaller/assets/135792762/19a86118-a16d-4ed3-9a8f-c29f2d9e12ed)
I had windows 11 but idk :)

**Comment by pointfeev** [comment]
There will be better failure outputs in v4.9.5
