### ISSUE TITLE
SteamCMD

### ISSUE THREAD

**Issue by MrFlambi** [pointfeev/CreamInstaller#121]
it seem that the program is blocked at "Setting up SteamCMD . . . 0%" 
(tried start in admin & non admin but no changes)

**Comment by MrFlambi** [comment]
After a shutdown & restart it work sorry for making a useless bug ticket

**Comment by ZonaiCat777** [comment]
Go to the files of the app and find steamCMD.exe open it and update it then relaunch creaminstaller
