### ISSUE TITLE
Ubisoft Connect games not showing up

### ISSUE THREAD

**Issue by cheat2winPT** [pointfeev/CreamInstaller#123]
Ubisoft Connect games started not showing up since v4.9.0

v4.8.1
![imagem](https://github.com/pointfeev/CreamInstaller/assets/136380137/831baf3f-264e-4f3c-ba4f-a7bcbc98be8b)

v4.9.5
![imagem](https://github.com/pointfeev/CreamInstaller/assets/136380137/9fd57ea8-7d08-45f1-916e-2ba4ec84fe2c)

**Comment by pointfeev** [comment]
Seems I made a bit of a typo, should be fixed in v4.9.6!

**Comment by cheat2winPT** [comment]
Thank you!
