### ISSUE TITLE
Cant open the zip file

### ISSUE THREAD

**Issue by snakkze** [pointfeev/CreamInstaller#124]
When i download the zip file from the latest release and try to open it, is it giving me a error message about not being permitted to open the zip file. After that a few seconds later the file deletes itself.

![grafik](https://github.com/pointfeev/CreamInstaller/assets/81985519/a4553d6b-100c-445b-983c-2eb5831cd2d8)

**Comment by pointfeev** [comment]
sounds like your antivirus, you need to resolve it and/or try another zip file handler such as 7-zip
