### ISSUE TITLE
Can't open the CreamInstaller.exe

### ISSUE THREAD

**Issue by Mav1212** [pointfeev/CreamInstaller#125]
The installer file won't open. Clicking on it does nothing except giving a spinning wheel on the mouse. Tried installing .NET Desktop Runtime 7.0.5 and that didn't fix the issue. Neither did any other versions of that program.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/110#issuecomment-1562811495
