### ISSUE TITLE
Toggle to hide games that don't have DLC

### ISSUE THREAD

**Issue by Chaython** [pointfeev/CreamInstaller#128]
###### Describe the new feature and its implementation OR how the existing feature could be improved:
IDK if this is already in some way implemented, as many titles have 'unknown' etc 'dlc', but there should be a way to hide games with no known DLC, for quicker sorting. Are a known compatibility list?

**Comment by pointfeev** [comment]
They don't get hidden from the pre-scan dialog because the whole point of it is to select which games you wish to scan FOR dlc. To determine if every found game has DLC would require a process that would simply slow down the program too much.

**Comment by Chaython** [comment]
What exactly is the flow of this app?
I don't understand why it's so compute heavy, especially for steam?
I don't know how Steam CMD works, but why doesn't this just check %steamappsdir% for appmanifest_###.acf for the numerical value then checking the value against steamdb? So not requiring Steam CMD etc?

**Comment by pointfeev** [comment]
because SteamDB is very selfish with it's gathered information, that's why. until I can find a way to use SteamCMD's app info function without the cumbersome prompt, there's nothing more that can be sped up for Steam
