### ISSUE TITLE
Unhandled exception error has occured in your application.

### ISSUE THREAD

**Issue by OsamaHeweitat** [pointfeev/CreamInstaller#13]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CreamInstaller.Epic.EpicLibrary.get_EpicManifestsPath() in C:\Users\zehme\Dropbox\PC\Documents\GitHub\CreamInstaller\CreamInstaller\Epic\EpicLibrary.cs:line 23
   at CreamInstaller.SelectForm.OnLoad(Boolean forceScan, Boolean forceProvideChoices) in C:\Users\zehme\Dropbox\PC\Documents\GitHub\CreamInstaller\CreamInstaller\Forms\SelectForm.cs:line 420
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Private.CoreLib.dll
----------------------------------------
CreamInstaller
    Assembly Version: 3.4.0.4
    Win32 Version: 3.4.0.4
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/CreamInstaller.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.322.12307
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.322.12307
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Threading.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Collections.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Private.Uri.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.322.12307
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Accessibility.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.322.12307
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Drawing.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Numerics.Vectors.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Diagnostics.Process.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Microsoft.Win32.SystemEvents.dll
----------------------------------------
Onova
    Assembly Version: 2.6.2.0
    Win32 Version: 2.6.2.0
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Onova.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Threading.Tasks.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Linq.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Text.Json.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.IO.Compression.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Text.RegularExpressions.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Microsoft.Win32.Registry.dll
----------------------------------------
Gameloop.Vdf
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/Gameloop.Vdf.dll
----------------------------------------
System.IO
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.IO.dll
----------------------------------------
System.Dynamic.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Dynamic.Runtime.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.322.12309
    CodeBase: file:///C:/Users/User/AppData/Local/Temp/.net/CreamInstaller/jTU5kN8j0U7smMmOyf3W4wmIb6L4kBA=/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by pointfeev** [comment]
Fixed in v3.4.0.5!
