### ISSUE TITLE
The program does not open after about 2 succesfull launches

### ISSUE THREAD

**Issue by Reverkhau** [pointfeev/CreamInstaller#132]
###### Describe the bug and/or provide an image of the exception dialog box:
The first time i tried to open the program it worked and i normally gave myself the DLC's.. But the second time it just doesnt work, yes i have the runtime, i turned off my antivirus and yes i extracted it. Nothing worked.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/117#issuecomment-1578704700

I'm not sure why this is such a common issue, .NET or your Windows version must just be fucking you. There's not much I can really do except perhaps fiddle with Mutex, though I doubt it's the problem.
