### ISSUE TITLE
disabling of specific dlc's

### ISSUE THREAD

**Issue by sakethaekka** [pointfeev/CreamInstaller#138]
I used creamAPI on Cities skylines epic games version. although it did unlock all dlcs and it was working perfect. It unlocked a bunch of unnecessary dlcs that  I do not intend to use, because of that my game also started lagging. Is there any way to unlock only selective dlcs or modify the dlc unlocks?

**Comment by pointfeev** [comment]
press the plus button to the left of the check boxes

**Comment by sakethaekka** [comment]
thank you so much for the reply! i did unselect the dlcs and installed them but unfortunately that is not working

**Comment by pointfeev** [comment]
Seems I may have interpreted the ScreamAPI config fields wrong, I should have it fixed in v4.9.8!
