### ISSUE TITLE
Downloading required DLC content automatically

### ISSUE THREAD

**Issue by womblee** [pointfeev/CreamInstaller#140]
###### Describe the new feature and its implementation OR how the existing feature could be improved:

Basically if you go into the DLCS tab of the game in steam, there is a ton of DLCS listed. The ones that won't work out of the box have their size listed in MB. Is there a way of downloading them at least for steam? Like some depot thing. Just some games require DLC files to be installed and I would like to know if there is a way to automate this or at least do it manually.

**Comment by pointfeev** [comment]
Lol no unfortunately not, that would require Steam login credentials that own the DLC, in which case you wouldn't even need the unlockers in the first place.
