### ISSUE TITLE
no steam games at all

### ISSUE THREAD

**Issue by Evidark** [pointfeev/CreamInstaller#141]
Cant add any steam game, i saw only ubi and egs games.

**Comment by pointfeev** [comment]
There must be something wrong with your Steam installation, I would try "repairing" or reinstalling Steam; see [here](https://github.com/pointfeev/CreamInstaller/issues/21#issuecomment-1120484314).

**Comment by bassj18** [comment]
same error with me as well.  new install  log give you !

![image](https://github.com/pointfeev/CreamInstaller/assets/54414889/99af411f-22cd-456f-ad7d-73588d3f87fb)

**Comment by bassj18** [comment]
> Cant add any steam game, i saw only ubi and egs games.

i same error so remove all steam files but left steamapp and exe and let redownload again and that fix it !
