### ISSUE TITLE
Game Crashing upon DLL loading

### ISSUE THREAD

**Issue by Nou4r** [pointfeev/CreamInstaller#153]
Creaminstaller installs the dlls and dependencies just fine, however when i launch the game and version.dll gets loaded it just causes an exception (screenshot)
![image](https://github.com/pointfeev/CreamInstaller/assets/12816677/0dc7da01-bef2-4c4a-9c39-78059d7fb338)

**Comment by pointfeev** [comment]
Read the note below "Bugs/Crashes/Issues" in the README/description.
