### ISSUE TITLE
Trash/virus, doesn't work, didn't install DLCs for my game, made my game crash and had to uninstall

### ISSUE THREAD

**Issue by HyunaTheHyena** [pointfeev/CreamInstaller#158]
Avoid this trash software please. Even after deleting this software my game still kept crashing

**Comment by en-joyer** [comment]
Same virus problem I have now.

**Comment by pointfeev** [comment]
Learn how to read, dumbass.

**Comment by HyunaTheHyena** [comment]
> Learn how to read, dumbass.

Kys

**Comment by pointfeev** [comment]
#40
