### ISSUE TITLE
cant find a specific game

### ISSUE THREAD

**Issue by sharkface0** [pointfeev/CreamInstaller#161]
cant find Payday 2 on here
![image](https://github.com/pointfeev/CreamInstaller/assets/123125878/8ee65b04-4188-4925-a616-a6be4180dda2)

**Comment by PsykoDev** [comment]
you gonna be taged as cheater if you unlock ll dlc of payday 2 and can't be reverted so don't do that

**Comment by PsykoDev** [comment]
otherwise if you really want do that just uncheck " Block protexted games " and payday 2 appear
