### ISSUE TITLE
Monster Hunter World

### ISSUE THREAD

**Issue by AzazelHD** [pointfeev/CreamInstaller#163]
Hello. CreamInstaller seems to do its job on the console, but then, when i try to run Monster Hunter World, game closes.

Do you have any idea why?

After uninstalling it with creaminstaller, game opens normally

**Comment by sdgsgsdf** [comment]
hi，Can you unlock the DLC of the world? I was kicked successfully, but in reality, I didn't

**Comment by Joackk** [comment]
hi, I had the same problem, I was prompted to successfully unlock the Ice Field dlc, but I didn't actually unlock it when I entered the game. Can you unlock it normally?
