### ISSUE TITLE
(HOI4) Hearts of Iron IV DLCs

### ISSUE THREAD

**Issue by Vqlom** [pointfeev/CreamInstaller#169]
The Hearts of Iron IV DLCs claim that they have been successfully installed, _however_, upon opening the game they aren't there yet and I have only the free starting DLCs.

**https://imgur.com/a/OvQIjJH**

Additional info: 
I have used CreamInstaller before for HOI4 and have had no issue, but I decided to preinstall my PC a few days ago and I might just not have something required for the process of installing the DLCs.

**Comment by BugB0ss** [comment]
For paradox games, you need to manually download the dlc into the dlc folder for it to be unlocked.

**Comment by azamet90** [comment]
> For paradox games, you need to manually download the dlc into the dlc folder for it to be unlocked.

where to download any dlc manually?
