### ISSUE TITLE
The DLL generated does not work well.

### ISSUE THREAD

**Issue by joezhouchenye** [pointfeev/CreamInstaller#17]
###### Describe the bug and/or provide an image of the exception dialog box:

The game is Total War: THREE KINGDOMS.

I have already downloaded a cracked steam_api64.dll online and it works well. I tested your program and have issues.

Cream_api.ini and steam_api64.dll are generated. The game can be opened and DLCs are unlocked as it looks.

However, when starts a new battle, the software crashes after some loading process.

My old cracked steam_api64.dll has no such problem and the size are different.

The working dll size is 648 KB, the generated dll size is 815 KB and the original dll size is 245 KB.

**Comment by pointfeev** [comment]
The program doesn't "generate" a DLL. It uses the latest 4.5.0.0 hotfix version from Christsnatcher's post embedded into the program itself and simply extracted without change during install, just like it says at the top of the read-me/description. Now as for TW:TK in particular: [see here](https://cs.rin.ru/forum/viewtopic.php?f=10&t=85837&p=2515346&hilit=CreamAPI#p2515346). You should always refer to the rin topic when you're having issues with a specific game.
