### ISSUE TITLE
Is there a fucntion to revert the changes that were made by creaminstaller

### ISSUE THREAD

**Issue by jgameryt** [pointfeev/CreamInstaller#170]
I don't see any option in the installer, or documentation on the forums or the Github page about what to do when the creaminstaller causes the game not to function.

Tried uninstalling only the dlcs, tried uninstalling all of the dlcs, but nothing changed, just an error report from the game.
Even reinstalled the game, still breaks. Would be really cool if we were just told about what cream installer changes so that we can simply restore it.

**Comment by pointfeev** [comment]
Step 9 under Usage
