### ISSUE TITLE
File to download SteamCMD

### ISSUE THREAD

**Issue by GodGunT** [pointfeev/CreamInstaller#172]
###### Describe the bug and/or provide an image of the exception dialog box:
![image](https://github.com/pointfeev/CreamInstaller/assets/139335576/2bd03192-0b3d-470b-aaeb-eb3a8341d47e)

**Comment by pointfeev** [comment]
I'll have the output and behavior of that exception fixed in v4.9.9, so if you get it again in that version please do re-open the issue with a new screenshot. However, this was likely a one-time thing and on Steam's part.
