### ISSUE TITLE
Failed To Write a Crucial Manifest Resource

### ISSUE THREAD

**Issue by lavishlovebomb** [pointfeev/CreamInstaller#175]
I've searched all over for a solution to this and couldn't find one. I've seen a few other people post about this same issue but no answers. How do I fix this? I didn't have any issues a few months ago. Thank you

![Screenshot (286)](https://github.com/pointfeev/CreamInstaller/assets/70613507/454338e3-6d97-4f67-8121-b23ff8743883)

![Screenshot (287)](https://github.com/pointfeev/CreamInstaller/assets/70613507/3b6beb78-4330-47f2-a5ef-4407d892aeaf)

**Comment by Xander6143** [comment]
Having this exact issue, but I just downloaded this
![image](https://github.com/pointfeev/CreamInstaller/assets/149345301/87653efa-e41f-43a6-a90b-b1df67ebd55d)
![image](https://github.com/pointfeev/CreamInstaller/assets/149345301/d48b175b-25ef-4434-bd50-7e45f039c810)

**Comment by pointfeev** [comment]
The exception will be fixed in the next version, however the popup itself happens because the file is in use (usually because the game is open) and therefore can't be wrote to.
