### ISSUE TITLE
False positives or a bug?

### ISSUE THREAD

**Issue by EthnSchwartz** [pointfeev/CreamInstaller#177]
I know that you already said that has many false positives because of the Koaloder, but this time can be different.
I was searching about the Wacatac and other .exes that can be false positives, and then i tried to download this like a false positive, but to make sure I did a fast research in the VirusTotal, and had many alarms.
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/2ef70ecc-93d1-4d31-aa50-befdadd48939)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/f026dd54-f9b2-43ae-9905-cb3c4aa5a99b)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/d563ba3c-3227-47c8-94d5-ac9e31c09300)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/c8d00112-b47e-4b89-9c93-b7ad7340466f)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/5139c896-c47d-40fd-953c-11a51bb3acbf)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/272499cb-731f-4702-aa0d-f7872c1bace4)
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/dc4961c1-3bf7-4173-bd61-349d3e6c0f82)

Than I tried to search for this positives in the source code on github and I didn't find it.
I don't too much about security and trojans, but I really don't like to see something saying that it has a Trojan.
If you can know something about, pls. I want to play stormworks without paying $50.
Sorry for my bad english.

**Comment by pointfeev** [comment]
It's still just a false positive; every detector has their own generic name for virus types, and every detector can detect the same thing as multiple different variants through different runs. The names I gave were just examples of the names I personally came across a while back.

**Comment by pointfeev** [comment]
#40

**Comment by EthnSchwartz** [comment]
Ok, i will trust you, but I cant run this code, windows stay saying that is a virus and don't let me run the .exe or open the .zip
![image](https://github.com/pointfeev/CreamInstaller/assets/34921951/9f3ac882-1fb3-4680-b8cc-b5f802ee29e1)
This one is already allowed, but still don't let me run the .exe, saying that has this wactac.

**Comment by pointfeev** [comment]
I'm not sure what anti virus you're using, but it would generally be easier to exclude the file(s) itself instead of each of the variants.

**Comment by EthnSchwartz** [comment]
i dont use any antivirus except the windows defender and MSERT to scan.

**Comment by Goggr5** [comment]
I also get the alert about the zip file as a whole 
![wwe](https://github.com/pointfeev/CreamInstaller/assets/82385094/07121fe1-9b6c-4aa6-b2c2-de6839bedd11)
