### ISSUE TITLE
Misleading Icon for an exe.

### ISSUE THREAD

**Issue by cl0rm** [pointfeev/CreamInstaller#180]
Currently the program Icon is that of an INF/INI file on Windows.
This is IMHO a bad practise to give a program / executable the same Icon as a Text-based file.
It is a thing that usually only virusses do. 
Also, I'm not sure if this logo is free to use, since it's a microsoft asset.
I recommend changing the icon to maybe a just a gear or similar. Even the generic ".exe/.com" icon would be better.
Otherwise great tool, Thank you very much for developing it!

**Comment by pointfeev** [comment]
I'll be adding a custom program icon in the next version. :)
