### ISSUE TITLE
SteamCMD download problem

### ISSUE THREAD

**Issue by Erfaniom** [pointfeev/CreamInstaller#182]
I for whatever reason cannot download SteamCMD through the CreamInstaller app, can you tell me where exactly I should put the SteamCMD.exe file in the C:\Program Data\CreamInstaller folder so that CreamInstaller will automatically realize it's there and won't try to download it?

**Comment by pointfeev** [comment]
C:\ProgramData\CreamInstaller\steamcmd.exe, downloaded from https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip
