### ISSUE TITLE
Auto Update question

### ISSUE THREAD

**Issue by Brain-war** [pointfeev/CreamInstaller#190]
###### Describe the bug and/or provide an image of the exception dialog box:
Hey, this really isn't a bug but I couldn't find any categories that really fit this.
I am really just wondering, do the DLCs automatically update themselves after CreamInstaller has installed them, or do I have to run CreamInstaller each time I want the DLCs to update?

**Comment by pointfeev** [comment]
No, DLCs do not automatically update themselves. Read the note under Usage instructions.
