### ISSUE TITLE
is arma 3 supported ?

### ISSUE THREAD

**Issue by NETarti** [pointfeev/CreamInstaller#191]
i want to get the dlc's to arma 3 but "arma 3" dosent pop off on the games list let me know if i can fix it or if its just not supported 
![image](https://github.com/pointfeev/CreamInstaller/assets/125475855/397dcd97-f3b0-4aa7-953f-40e1de48f2d6)
![image](https://github.com/pointfeev/CreamInstaller/assets/125475855/ccc2d4aa-e81b-4f64-b56d-765541de749f)

**Comment by pointfeev** [comment]
ARMA 3 has battleye, so the dll-tampering dlc unlockers this program uses probably won't work on it and attempting to use them (especially with Koaloader) has a pretty good chance to get you banned, if you can even make it past the launcher. Press the question mark to the right of the Block Protected Games checkbox on the main scan dialog for more info on the feature, and just press Cancel and uncheck that box if you wish to scan it and risk installation. You should look into the ARMA 3 thread on cs.rin.ru and see what they say about dlc unlocking before doing anything.
