### ISSUE TITLE
Add CreamAPI v5.0.0.0

### ISSUE THREAD

**Issue by iArtorias** [pointfeev/CreamInstaller#195]
There's a new version of the CreamAPI since Jan. 8 with some huge changes/updates. You might want to check it out.

**Comment by iamrandom09** [comment]
Can you link it?

**Comment by iArtorias** [comment]
> Can you link it?

https: //cs.rin.ru/forum/viewtopic.php?f=29&t=70576

**Comment by ChazmerW** [comment]
Is this getting this update?

**Comment by pointfeev** [comment]
I'll be migrating back to CreamAPI in the next version as a result of #238.
