### ISSUE TITLE
Status text not visible

### ISSUE THREAD

**Issue by Kaan2106** [pointfeev/CreamInstaller#2]
While using the first and second time the installer's status text isn't readable at all.
Only lower-half of text is shown

Screen https://prnt.sc/21xwwb6

**Comment by pointfeev** [comment]
I'm unable to replicate this issue no matter what I try, so more information would be very helpful.

Does this still occur after the migration to Visual Studio 2022 and .NET 6.0?
Is Windows and .NET 6.0 up-to-date?

**Comment by pointfeev** [comment]
Considering it's been a month with no response, and I've been unable to reproduce the issue, I'm going to go ahead and close this issue.
