### ISSUE TITLE
Can't Find All DLCs for THE IDOLM@STER STARLIT SEASON AppID 1046480

### ISSUE THREAD

**Issue by meochan913** [pointfeev/CreamInstaller#20]
Hi!
The installer is having an issue with finding all of the DLCs of this game THE IDOLM@STER STARLIT SEASON AppID 1046480.
This game has 142 DLCs and CreamAPI is able to unlock them all (I'm currently using it).
But the CreamInstaller can only find 65 DLCs in the configurator. I've tried to rescan it but the result is the same.
![image](https://user-images.githubusercontent.com/48139724/166177162-5a42b2f7-543a-488f-b9ea-c118f67d110a.png)
![image](https://user-images.githubusercontent.com/48139724/166177178-773db35c-5d09-4c0b-b690-0ac79ef712dc.png)

**Comment by meochan913** [comment]
Adding the link to the game. 
https://steamdb.info/app/1046480/dlc/

**Comment by pointfeev** [comment]
A possible explanation is that the steam store API has a limit of around 200 queries every 5-10 minutes (I think those are the right numbers), which can cause some store queries to be missing should you scan a ton of games at once with hundreds of DLCs total. Therefore, you can try making sure your steam query "limit" is fine by waiting about 5-10 minutes and then only selecting the offending game in the pre-scan dialog box. Unfortunately there's nothing I can really do about this query limit, so the program can in fact skip some things due to that. Though, it's usually not an issue, because SteamCMD doesn't have any kind of limit, and almost always gets all of the important (if not every single) DLC.

**Comment by meochan913** [comment]
Hey man,

Thanks for the reply!
I left the program the whole night and I've retried the scan just this game just now.
Everything is the same it's still grabbing the first 65 of the DLCs.
It's really weird cuz it can grab every DLC for Monster Hunter Rise and it has 110+ DLCs.

As for the SteamCMD query issue, I'm not sure why it's returning nothing for you cuz I'm in Canada and I was able to query it just like any other game. Maybe because my account is a Chinese account?

**Comment by meochan913** [comment]
The missing DLCs actually contain lots of non-micro-transactions stuff like the story DLCs and new costumes and new characters. As I was saying before, I'm using my own creamAPI profile to unlock those DLCs and they are working properly.
[1046480.zip](https://github.com/pointfeev/CreamInstaller/files/8603452/1046480.zip)
I only found the vdf file in the appinfo folder.
Thank you so much for your time and I really appreciate your help man!

**Comment by pointfeev** [comment]
Ah, if you only found the vdf that explains things. That means it's not successful in querying the Steam store, so I'll have to see why that is.

**Comment by meochan913** [comment]
Thank you, man! Please let me know if you need my help!

**Comment by pointfeev** [comment]
Alright, I've found a couple of possible issues related. First, I was able to "emulate" CreamInstaller scanning this game, and found that so long as I was on a Canadian/Japanese VPN, it would finally successfully query the steam store for those missing DLCs after I hit rescan a couple times.

Thus, in v3.4.3.0, I'm going to make it such that all games are queried on the store first before any DLC (to prevent them from missing the query limit), and such that all games MUST finish a store query, meaning store queries will be waited on and no DLC from the steam store should ever be missed anymore.

**Comment by meochan913** [comment]
Thanks for your hard work man!
But I've got another issue:
After upgrading CreamInstaller to the latest version and opened with Admin privilege, The app will be stuck at 0% for this game.
I've only selected this game and the app will just hang there (responsible but not progressing).
![image](https://user-images.githubusercontent.com/48139724/166305655-43b2f4a2-7c9e-43fa-abcd-ddecd78f4ad7.png)

**Comment by pointfeev** [comment]
That's because of the changes I just mentioned. Either your query limit is up or steam is thinking you're not in the correct region for that game. Have you tried a Toronto or Japan VPN?

**Comment by pointfeev** [comment]
The program parses this steampowered: [https://store.steampowered.com/api/appdetails?appids=1046480](https://store.steampowered.com/api/appdetails?appids=1046480)

When I attempt to query (with that link), it shows this for me:
![image](https://user-images.githubusercontent.com/15071274/166307642-fce55de8-ca48-4379-ab51-d27ff888317d.png)
I had it show the game's details once before, but now I literally can't get it to query this game successfully even with both system-wide and browser VPN.

This seems to be a Steam issue, I don't think there's anything I can do about it unfortunately.

**Comment by meochan913** [comment]
Yeah, I've tried with and without a Japan VPN. All its returns were false...
Looks like the API is treating this region-locked game differently.
You are right and there's nothing we can do about it.
I really appreciate your time and help with this issue and hopefully, Steam API for this game will work again soon.
