### ISSUE TITLE
Dll cannot be trusted

### ISSUE THREAD

**Issue by rykou** [pointfeev/CreamInstaller#200]
###### Describe the bug and/or provide an image of the exception dialog box:
when starting a game 
![Screenshot 2024-02-16 161007](https://github.com/pointfeev/CreamInstaller/assets/15199165/9066d6c1-0d0f-4dbc-bfde-82f278794779)
Unstrusted win file 

![Screenshot 2024-02-16 161416](https://github.com/pointfeev/CreamInstaller/assets/15199165/36269724-204e-45cf-b5a0-d38e940337f6)

**Comment by pointfeev** [comment]
You can't use it on games with Easy Anti-Cheat, since it acts much like a cheat would how it unlocks DLC.
