### ISSUE TITLE
Train simulator

### ISSUE THREAD

**Issue by jamesotas** [pointfeev/CreamInstaller#201]
Hello, i have tried to unlokc all dlcs in Train simulator but it is not working.
i would love to if you would do something with it.
have a nice day.

**Comment by LarsIsHere** [comment]
It does work, atleast for me. You just have to re-run creaminstaller often. Its just that Train Simulator has a bunch of conflicting dlcs, so you shouldnt install them all. Also you need the (pirated) dlc files installed first.

**Comment by jamesotas** [comment]
So i need pirated Train simulator or? I bought like 4 dlc on steam so what do you mean by "you need the pirated dlc installed first"?

**Comment by LarsIsHere** [comment]
creaminstaller simply tells train sim that you own the dlcs. but you dont have the dlcs present. it doesnt download them for you. you need a cracked/priated version of the dlc from like rutracker or whatever
