### ISSUE TITLE
Opens then Closes

### ISSUE THREAD

**Issue by githubUser01946** [pointfeev/CreamInstaller#204]
I have installed the Installer on my Steam Deck and the app allows me to select the game I want to unlock, it then closes as soon as I click ok. 

No DLC options come, just closes.

**Comment by Zero8000** [comment]
Can confirm this has been happening for a while on PC as well.

**Comment by githubUser01946** [comment]
> Can confirm this has been happening for a while on PC as well.

Have you installed this? [.NET Desktop Runtime 8.0.2](https://download.visualstudio.microsoft.com/download/pr/84ba33d4-4407-4572-9bfa-414d26e7c67c/bb81f8c9e6c9ee1ca547396f6e71b65f/windowsdesktop-runtime-8.0.2-win-x64.exe)

I don't have issues with it on PC, mine is linux.

**Comment by githubUser01946** [comment]
Any help for my issue @pointfeev ?

**Comment by pointfeev** [comment]
> Any help for my issue @pointfeev ?

I don't have time to look into it right now, your best bet is to install the unlocker you need manually until then.

**Comment by githubUser01946** [comment]
I don't know of any other unlockers, only this one but ok. I'll wait for your update whenever that happens to be. 🙂

**Comment by pointfeev** [comment]
#102
