### ISSUE TITLE
Can't download DLC

### ISSUE THREAD

**Issue by ZacharySolum** [pointfeev/CreamInstaller#206]
###### Describe the bug and/or provide an image of the exception dialog box:
![f38d84044b5b8b00f7fb09084d9bd396](https://github.com/pointfeev/CreamInstaller/assets/165830709/1b074500-1e9f-4a89-833c-661b6ac6f6f1)
It keeps giving me this error when I try to Generate and Install.

**Comment by Xryphon** [comment]
Did you try disabling your antivirus?

**Comment by pointfeev** [comment]
I've never encountered an "Incorrect function." before, and I can't find anything online to explain it, so I'm not quite sure what's going on there. However, usually that kind of write error is normal and shows up due to antivirus or the game being open while you're trying to install to it.
