### ISSUE TITLE
v4.10.1 stuck on hoi4 dlc 228050

### ISSUE THREAD

**Issue by msalkeld57** [pointfeev/CreamInstaller#208]
v4.10.1 doesnt work on hoi4. When "gathering and caching" the game, it gets stuck on "Remaining DLCs (1): 2280250" permanently. Tried a fresh install and tried a friends PC and got the same issue

**Comment by isorlas** [comment]
happened to me too, also messed up my settings but that didnt matter

**Comment by pointfeev** [comment]
It worked fine in my testing just now. You should keep in mind that some DLC may take quite a long time to query due to how SteamCMD is currently hacked together.
