### ISSUE TITLE
macOS and Linux Support

### ISSUE THREAD

**Issue by Xryphon** [pointfeev/CreamInstaller#209]
###### Describe the new feature and its implementation OR how the existing feature could be improved:

Currently the 5.1.0.0 version of creamAPI as listed on cs.rin.ru has some major improvements; the latest version provided compatability with both Linux and macOS officially.

It'd be nice to see a version of CreamInstaller appear on macOS and Linux to streamline the DLC cracking process, especially for Paradox games (looking at you EU4...)

**Comment by pointfeev** [comment]
#102 #195
