### ISSUE TITLE
Custom game version

### ISSUE THREAD

**Issue by Dara1LT** [pointfeev/CreamInstaller#212]
###### Describe the new feature and its implementation OR how the existing feature could be improved:
Would be nice if we could choose at what game version we want to apply creamapi, for example I have legit beatsaber (latest version) and downgraded for mod support, cant really apply cream to older version. Iam fully aware that cracked game version exist but due to mod assistant crack some mods dont work. So i have to use legit version of mod assistant in order to play with mods

**Comment by pointfeev** [comment]
not possible
