### ISSUE TITLE
"An established connection was aborted by the software in your host machine"

### ISSUE THREAD

**Issue by Klastan** [pointfeev/CreamInstaller#219]
###### Describe the bug and/or provide an image of the exception dialog box:

I tried to unlock Hoi4 dlcs, but it didn't allow me. This problem is also appearing when I try to unlock other Steam game's dlc.

![Screenshot 2024-05-15 213905](https://github.com/pointfeev/CreamInstaller/assets/169941720/bc02f8c6-4ca4-41a5-8ce3-8ccdd518c4aa)

**Comment by pointfeev** [comment]
You may need to diagnose your system network adapters and/or anything on the system that could be interrupting network connections such as perhaps an antivirus.
