### ISSUE TITLE
SteamCMD output string exception

### ISSUE THREAD

**Issue by illianoaoi** [pointfeev/CreamInstaller#22]
###### Describe the bug and/or provide an image of the exception dialog box:
Some error with
<img width="504" alt="2022-05-08_16-26-32" src="https://user-images.githubusercontent.com/20558618/167290058-c2f18d4e-42d8-49b2-8d76-447f83b5fd87.png">

**Comment by pointfeev** [comment]
I'm not entirely sure why you're having this issue, but I've pushed v3.4.3.1 in an attempt to remedy it! Please tell me if that fixes it or not.

In this update, I've also attempted to fix the strange sizing issue with the "Block Protected Games" checkbox on other languages, so please do tell me if that is fixed or not! :)

**Comment by illianoaoi** [comment]
Thank for your quickly reply. v3.4.3.1 not fix.
<img width="1059" alt="Screenshot 2022-05-09 142519" src="https://user-images.githubusercontent.com/20558618/167360701-3875209a-aaba-4ed5-9b41-a76bd3093b90.png">

**Comment by pointfeev** [comment]
Alright then, I've just pushed v3.4.3.2, see if that fixes it. Sorry that it may take a couple of updates to hammer down this issue, it's not inherently obvious why this rare exception is occurring. If this update doesn't fix it, then in v3.4.3.3 I'll simply put it in a try catch as that's the only other thing that can be done.

**Comment by pointfeev** [comment]
Has this issue been fixed? If there's no response within a week or so I'll just close it.
