### ISSUE TITLE
System Unauhtorized Access exception

### ISSUE THREAD

**Issue by Spyton1** [pointfeev/CreamInstaller#222]
![CreamApiBug](https://github.com/pointfeev/CreamInstaller/assets/171187717/52035955-ba28-4b6a-8a90-60087116bb05)
###### Describe the bug and/or provide an image of the exception dialog box:

**Comment by lonewolf0708** [comment]
Try running it from another location other than "My Documents" or try right-clicking and running as administrator (NOT RECOMMENDED/FOR TROUBLESHOOTING ONLY!) I run from a USB stick in the root (E:\CreamInstaller.exe) just fine normal/not Admin.

**Comment by Spyton1** [comment]
I have tried those things lonewolf0708. It pops up the same message no matter where I store it, Desktop, Documents, Program files, everywhere even on a secondary hard drive with or without Admin Access, even tried running it in Compatibility for windows 8. Thank you though.

**Comment by pointfeev** [comment]
Did you somehow or for some reason create a Steam library in your documents or install a game there?

**Comment by Spyton1** [comment]
C:\Users\Tony\Documents\steamapps\common 
^That does seem to be the spot where Steam is installing files, though I do not remember changing that and it should be the default location when steam chose to install on my computer.

I can try moving them to their own folder outside of documents and see if that fixes it.

**Comment by pointfeev** [comment]
You should definitely not be installing games in your Documents folder, I am surprised none of your games have had issues with it.

**Comment by Spyton1** [comment]
Well I moved all the stuff from there and it worked, idk how I managed to install into that folder in the first place or have no issues for 7 years but all is well that ends well. Thank you.
