### ISSUE TITLE
Sort by name doesn't always sort by name

### ISSUE THREAD

**Issue by kotenok2000** [pointfeev/CreamInstaller#227]
###### Describe the bug and/or provide an image of the exception dialog box:
![image](https://github.com/pointfeev/CreamInstaller/assets/8822292/6622d983-8531-4928-915d-77030fffe8c4)

**Comment by ZotoBro** [comment]
It sorts by name then platform, so I think this is just intended behaviour and not a bug.

**Comment by pointfeev** [comment]
Strings were being sorted using ordinal comparison. This will be fixed in the next version by using culture-specific comparison.
