### ISSUE TITLE
New update windows in high resolution!

### ISSUE THREAD

**Issue by Damn3d** [pointfeev/CreamInstaller#23]
Hi !

That's the second time i can't use the "update windows" at launch on my TV resolution (3840x2160).

I can't enlarge the window and when i move into the window, i just can read (hardly) the patch notes and... that's all! ;)

Thanks :)
![2022-05-11_192508](https://user-images.githubusercontent.com/22372482/167910131-222ea3fd-d6e4-4166-9149-c6b88e851fef.png)

**Comment by pointfeev** [comment]
I'm not sure I understand, is Windows making the program too small or the buttons too big? I'm not sure what I can even do about either of those issues either, but I'll look into it.

**Comment by pointfeev** [comment]
More information would be appreciated, otherwise I'll close this issue next week or so.

**Comment by Damn3d** [comment]
Sorry for the delay, the window is too small and I can't enlarge it manually by putting for example the cursor in a corner and stretching (like any classic window), so I'm stuck.


![2022-06-10_231622](https://user-images.githubusercontent.com/22372482/173152384-2e945ac7-5375-432f-8d73-f97a0b02ceef.png)

**Comment by pointfeev** [comment]
I'm assuming you're talking about Windows' Scale feature? Personally it works fine with me when using the recommended zoom levels, but I use a standard screen size and ratio of 1920x1080. I'll experiment with WinForm's auto sizing features to see if I can find a solution for you. :)

**Comment by pointfeev** [comment]
Alright I've converted forms into using WinForm's AutoSize. Can you test [this](https://github.com/pointfeev/CreamInstaller/releases/tag/v3.5.2.0) version and see if it still scales strangely?

**Comment by Damn3d** [comment]
Thanks but i can't tell you right now, i need to wait the next version to see the update window :D

**Comment by pointfeev** [comment]
Ah of course; I have a potential bug fix upcoming so we'll see then lol.

**Comment by pointfeev** [comment]
Whilst I await a feedback on said upcoming bug fix, feel free to test if the update window is fixed with [this debug version](https://www.dropbox.com/s/ungv4nxk7rtqe4w/CreamInstaller.exe?dl=1) if you'd like.

**Comment by pointfeev** [comment]
By the way, v3.5.3.0 has been released. I would appreciate if you could provide feedback as to whether or not this issue is fixed! :)

**Comment by Damn3d** [comment]
It's perfect dude!
Thanks a looooooot :)
![2022-06-18_161436](https://user-images.githubusercontent.com/22372482/174442403-81278024-91f8-4064-b2a2-a17d5306115a.png)
