### ISSUE TITLE
Steam client recent update now detects SmokeAPI

### ISSUE THREAD

**Issue by JakeLBeans** [pointfeev/CreamInstaller#238]
Recent Steam update has now started to detect SmokeAPI. Had a warning on first start up of Steam the other day to remove it before I could open Steam again.

**Comment by malfestio** [comment]
Same here
![image](https://github.com/user-attachments/assets/4bbb7ee8-e0a8-4fa5-b1f0-339de2ac43ff)

**Comment by pointfeev** [comment]
oh now that's interesting. I'll have to definitely see what it looks like for CreamAPI now

**Comment by pointfeev** [comment]
I'll be migrating back to CreamAPI in the next version as a result of this problem and multiple other problems caused by how outdated SmokeAPI has become. #195
