### ISSUE TITLE
Installer no longer working with the Stellaris Paradox Launcher due to the Overlord update.

### ISSUE THREAD

**Issue by RealDashU** [pointfeev/CreamInstaller#24]
###### Describe the bug and/or provide an image of the exception dialog box:

Looks like Paradox had a new update for the game for the Overlord "expansion". Unsure of what exactly the issue is but I've tried common troubleshooting to get it to work, even reinstalled both the installer and Stellaris as is. CreamInstaller states the DLC were successfully installed/generated but does not show up in-game, or in the launcher.

**Comment by pointfeev** [comment]
This program does not download DLC files for you, it only (like it says in the description) applies CreamAPI or ScreamAPI to legitimately owned Steam or Epic games to make those games believe you own DLCs. Should the game not come with the DLCs already installed in the initial package (as is the case for all Paradox games), for rather obvious reasons, you have to find and install DLC files to the game yourself. DLCs do not show up in the Paradox Launcher until they're installed to your game. See [here](https://cs.rin.ru/forum/viewtopic.php?p=2599093#p2599093) for pre-Overlord DLC files and [here](https://cs.rin.ru/forum/viewtopic.php?p=2599698#p2599698) for Overlord DLC files.
