### ISSUE TITLE
Unable to detect game on separate hard drive?

### ISSUE THREAD

**Issue by applita059** [pointfeev/CreamInstaller#243]
I have steam games installed on different hard drives and CreamAPI isn't able to detect the steam games on separate drive.  Is there a way to get it to search my other drive?

**Comment by peter9811** [comment]
+1
I have game exported from my internal drive to one external to have some free space
Any way to add extra folders to manually search?

Thanks

**Comment by Valyrius** [comment]
CreamInstaller reads this file to get all of the Steam library paths `C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf`
If using the Steam storage settings doesn't work for some reason, then perhaps you can try to add one manually by editing the file itself.

Just make sure that its a valid Steam library.
![image](https://github.com/user-attachments/assets/4459d97b-a878-4573-947c-406de00cf739)

**Comment by applita059** [comment]
It was my mistake, the game I was trying was found when I enabled Block Protected Games.  It works great.  But good to know the path can be possibly edited.  Thanks.

**Comment by pointfeev** [comment]
I should probably move that button to the scan selection form and make it a bit more obvious. Glad you figured it out though.

**Comment by peter9811** [comment]
> I should probably move that button to the scan selection form and make it a bit more obvious. Glad you figured it out though.

In my case is not the button
I have a couple of games on a external storage, I just copy and move on. But are from different sources, no just Steam
It is possible to add a button to scan specific folder or drive?
Thanks

**Comment by pointfeev** [comment]
Are they legitimately purchased Steam/Epic/Ubisoft games? The DLC unlockers are only for legitimate games; game cracks have their own methods of unlocking DLCs.

**Comment by peter9811** [comment]
> Are they legitimately purchased Steam/Epic/Ubisoft games? The DLC unlockers are only for legitimate games; game cracks have their own methods of unlocking DLCs.

I have like 3 drives, 2 of them are 100 % legit, from UPlay, Steam and even Epic, but I got some from the ocean :), I'm having problems with both... 
I'm checking the folder paths, and I found this, maybe because is no correct tag the letter drive? That' probably gonna solve the first problem
![image](https://github.com/user-attachments/assets/f48f2598-e258-4c2e-88d8-ee9c75fdbb1c)

What about the not legit ones. Do you know what's the method? I have zero idea about that, but I just got a couple and I want to try to maximise the game experience

**Comment by pointfeev** [comment]
Depends on where you got them and all, but most non-legit games would already come with all the DLC as well, you wouldn't need to worry about it.

This is how my libraryfolders.vdf looks like, it works fine for me:
![image](https://github.com/user-attachments/assets/31002dbb-b874-4179-b705-ec53ae61843c)
The program only reads the "path" parameter from that, nothing else should matter to the program.

It then proceeds to that directory's steamapps folder and reads multiple things from the *.acf files in there, one of mine looks like this:
![image](https://github.com/user-attachments/assets/453696a0-b6db-45c1-adb9-f8bdc0f19875)
In particular, it reads from the ACFs:
- appid
- installdir
- name
- buildid (for caching)
- betakey (for the branch, it's not required to be in the files, "public" will be assumed if not)

You can see all of this in the code here: https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Platforms/Steam/SteamLibrary.cs.

**Comment by peter9811** [comment]
> Depends on where you got them and all, but most non-legit games would already come with all the DLC as well, you wouldn't need to worry about it.
> 
> This is how my libraryfolders.vdf looks like, it works fine for me: ![image](https://private-user-images.githubusercontent.com/15071274/352782977-31002dbb-b874-4179-b705-ec53ae61843c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjc2MjEsIm5iZiI6MTcyMjEyNzMyMSwicGF0aCI6Ii8xNTA3MTI3NC8zNTI3ODI5NzctMzEwMDJkYmItYjg3NC00MTc5LWI3MDUtZWM1M2FlNjE4NDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDAwNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMGNjODhmNzJiZTE0NTRmM2E5MGFkZGQ5MDM3MDU1NGU4YjdhYzY5NTlmZWU0ZDdmY2RmMjFhMWNkMmQxOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mDMiptO-lWbFAmU5xbLIC0oHCfWRgAXE2F7YVadad9o) The program only reads the "path" parameter from that, nothing else should matter to the program.
> 
> It then proceeds to that directory's steamapps folder and reads multiple things from the *.acf files in there, one of mine looks like this: ![image](https://private-user-images.githubusercontent.com/15071274/352783250-453696a0-b6db-45c1-adb9-f8bdc0f19875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjc2MjEsIm5iZiI6MTcyMjEyNzMyMSwicGF0aCI6Ii8xNTA3MTI3NC8zNTI3ODMyNTAtNDUzNjk2YTAtYjZkYi00NWMxLWFkYjktZjhiZGMwZjE5ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDAwNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZjAxMzhmOWM2NmY1YzQ5ZDM2YzZkMGM4NzczOGZiZDNhOWFkNDg2YjUzYzMxMGVkMWVmZDI3MjczNDA2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.coeX7sko6IN9NhD9xnVd5GDyTm4r0AbSXA3sgJCJPJc) In particular, it reads from the ACFs:
> 
> * appid
> * installdir
> * name
> * buildid (for caching)
> * betakey (for the branch, it's not required to be in the files, "public" will be assumed if not)
> 
> You can see all of this in the code here: https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Platforms/Steam/SteamLibrary.cs.

For the first, that's mean that, can I just add the other drive path (legit ones) to try to find some games?
But no with the other, becase those last ones are no legit?

And, their are just on a folder "X:\Games\", something like that. But I'm not sure about if the DLC are activated or not... Is something that I can do?
Thanks
