### ISSUE TITLE
Paradox launcherv2 not starting up

### ISSUE THREAD

**Issue by Baumart** [pointfeev/CreamInstaller#245]
Hallo, today Paradox fixxed something the luchner, all of my firends and me have the same error massage: "an error has occured : Unable to locate the config file", we reinstalled and no we not updatedet the launcher.
HOIV = "the appid value cannot be empty"
Stellaris = want start
CK3= want start
paradaox launcher = "the appid value cannot be empty" 

BUT language = english not helps

**Comment by pointfeev** [comment]
When the Paradox Launcher updates while an unlocker is installed to it, you need to either run the install again, as it will repair the launcher automatically, or use the right click menu "Repair" option:
![image](https://github.com/user-attachments/assets/0a035041-9beb-4894-876d-7e4807a109fb)

If that doesn't work, try uninstalling with the program, and then installing again.
