### ISSUE TITLE
Hearts of Iron IV DLCs not unlocking 

### ISSUE THREAD

**Issue by VinVei** [pointfeev/CreamInstaller#247]
I've installed the DLCs on Hearts Of Iron IV. After doing everything it said that my operation was a success. I go into the game, and no DLCs are unlocked, None at all. But I did notice that it said "Subscription Active" but there are no DLCs. I reinstalled everything, but nothing worked. What seems to be the fix here?

**Comment by pointfeev** [comment]
Look at the note under usage instructions.
