### ISSUE TITLE
Dont force window to be on top

### ISSUE THREAD

**Issue by Simzy** [pointfeev/CreamInstaller#26]
###### <u><b>Describe the new feature and its implementation OR how the existing feature could be improved:</b></u>
Essentially as the title suggests, i want to leave it scanning but do other stuff on my pc but the window is always on top of others, perhaps not force it on top of all other windows.

**Comment by pointfeev** [comment]
I make it always on top because It's meant to be a relatively fast-use program, but I can see how that may get irritating and I realize it can take some time should you choose a lot of games, so I'll definitely take it into consideration. :)

**Comment by pointfeev** [comment]
All program forms will no longer be TopMost in v3.5.0.2! :)
