### ISSUE TITLE
Creaminstaller dont work.

### ISSUE THREAD

**Issue by Mabbe17** [pointfeev/CreamInstaller#264]
First when we download the file its not zip file as its write when we click on it on github. Its only a dossier with the creaminstaller in it. Then I click on it and its not working. I think you have to check your file on github to see the file on it is ok.  You will see I am right about the file on github.    

Also I used the Stellaris DLC unlocker and it worked find. But not Creaminstaller.  I dont why.

**Comment by pointfeev** [comment]
The uploaded ZIP file is fine. Make sure you're attempting to open the file with the correct program. I would recommend downloading and using 7-Zip.

**Comment by Mabbe17** [comment]
![Cream installer](https://github.com/user-attachments/assets/3f52a240-ad72-4936-9dc2-30711d23de12)
Thats the file I received whan I dont the creaminstaller

**Comment by Mabbe17** [comment]
As you see its not a zip file we downloading.

**Comment by pointfeev** [comment]
https://www.solveyourtech.com/how-to-change-what-program-opens-a-file-in-windows-11-a-simple-guide/
https://www.supportyourtech.com/tech/how-to-change-what-program-opens-a-file-windows-11-a-step-by-step-guide/

**Comment by Mabbe17** [comment]
I click on the program and Nothing happend

**Comment by Mabbe17** [comment]
![creaminstaller 2](https://github.com/user-attachments/assets/72da1018-9f64-487a-a5b7-d53cc2a08c64)
Its what I have on the dossier and its not working and I cant have the open with option too.

**Comment by pointfeev** [comment]
You need to extract it from the archive/dossier before running it. Please read the FAQ.
