### ISSUE TITLE
Once I chose a game to scan it doesn't do anything

### ISSUE THREAD

**Issue by SpicyDandelion** [pointfeev/CreamInstaller#266]
![cream](https://github.com/user-attachments/assets/29600096-e81e-43c3-b7ed-11e2e9117c09)
![cream2](https://github.com/user-attachments/assets/123ba1b4-8286-4c50-9752-5d6101e736da)
 
I mostly wanted to see if this would work with Palia...but nothing was happening. So I clicked on elden ring too...same thing. I clicked "ok" is that what you're supposed to do? "save" and "load" did nothing

**Comment by SpicyDandelion** [comment]
ah I just deleted and reinstalled and that fixed it. I just don't know how to get it to work...I read that the dlc has to be added manually...but I don't think that's how Palia works so idk if it will work for this game. You buy in game currency, to unlock the dlc....any advice?

**Comment by pointfeev** [comment]
https://cs.rin.ru/forum/viewtopic.php?f=10&t=137416
