### ISSUE TITLE
CreamInstaller doesn't add CreamAPI DLL

### ISSUE THREAD

**Issue by Queenofdragons6** [pointfeev/CreamInstaller#268]
I've tested this on two games and it worked on neither, but Auto-CreamAPI 2 worked on both (well...in that it had an effect). According to Auto-CreamAPI 2, the games didn't have the CreamAPI DLL applied.

**Comment by Queenofdragons6** [comment]
...Actually, turns out both games were ones where the DLC files needed to be manually put in for CreamAPI to work.

**Comment by pointfeev** [comment]
Did the game have the CreamAPI DLL installed correctly then or not? I'm not sure I would trust what Auto-CreamAPI 2 says, especially if it's using file hashes to determine that like I am. I would check yourself using the right-click context menu's directory buttons.

If it's not installing them for sure, can you also make sure your antivirus isn't for some reason deleting them automatically?

**Comment by Queenofdragons6** [comment]
Hmm... It might be working properly after all, since the steam_api file has a different timestamp.
