### ISSUE TITLE
dlc list update

### ISSUE THREAD

**Issue by re1ocate** [pointfeev/CreamInstaller#269]
###### Describe the bug and/or provide an image of the exception dialog box:

when a new DLC is released, the list is not updated if it was previously downloaded, to force the update, I had to delete all the JSON files from the ProgramData\CreamInstaller\appinfo directory

**Comment by pointfeev** [comment]
There is a Refresh Query button in the right click context menu for this. It doesn't delete the JSON for steamcmd.net in v5.0.0.0 though, that's a known issue I have already resolved, but not pushed yet as I haven't had time to do everything else I want for the next release.

This shouldn't matter though, as the cache (those files you mention) are invalidated by the program after 10 minutes for games and after 20 minutes for DLCs. See [here](https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Platforms/Steam/SteamCMD.WebAPI.cs#L23) and [here](https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Utility/ProgramData.cs#L55) if you wanna know how that works.
