### ISSUE TITLE
Unsupported old version of SteamUser004: 4

### ISSUE THREAD

**Issue by MarcoReckless** [pointfeev/CreamInstaller#28]
Greetings,
I've used this software to install **CreamAPI/SmokeAPI** on a few games and it worked just fine (as long as the DLC files were there).

Today I decided to try on **Final Fantasy XV**, this game had a **pre-order DLC** that is unobtainable nowadays, so I went on and grabbed the DLC files and added the game to the CreamInstaller configuration, after the installation I'm met with this error:

_"Unsupported old version of SteamUser004: 4"_

This is probably **unrelated to CreamInstaller** itself but I wanted **some help** since I'm pretty new to DLC unlockers in general.
I used to get this on **Tales of Arise** as well when the **first SmokeAPI version of CreamInstaller** dropped but since the **second update** it fixed itself.

![Screenshot_1](https://user-images.githubusercontent.com/13008862/169531662-89e8d966-50e5-4fea-92a9-5aeeaad7f7cc.png)
![Screenshot_2](https://user-images.githubusercontent.com/13008862/169531667-c97c5b7f-db6b-4c3e-a54e-9d4144394dbf.png)

**Comment by pointfeev** [comment]
Definitely report this to acidicoala. See [here](https://github.com/pointfeev/CreamInstaller/issues/27#issuecomment-1130702798) for more information.

**Comment by MarcoReckless** [comment]
I'm going to leave a comment on his thread then.

**Comment by pointfeev** [comment]
SmokeAPI v1.0.1 claims to have fixed it btw! :)

**Comment by MarcoReckless** [comment]
Can confirm, the game is able to start now.
