### ISSUE TITLE
Missing function in Address book

### ISSUE THREAD

**Issue by Feramance** [pointfeev/CreamInstaller#29]
I am getting an error when trying to launch Space Engineers saying that SmokeAPI is missing the function mentioned below. Any fix for this please?
![image](https://user-images.githubusercontent.com/38938175/170890956-d7ef2de7-3883-4642-b131-aeccaaff9f79.png)

**Comment by pointfeev** [comment]
Report it to acidicoala [here](https://github.com/pointfeev/CreamInstaller/issues/28#issuecomment-1133016617).
