### ISSUE TITLE
DLCs do not unlock

### ISSUE THREAD

**Issue by Com3Carne** [pointfeev/CreamInstaller#30]
I don't know if it's a bug or not. But when I disable a DLC, it creates a **SmokeAPI.json** file with **"unlock_all": false** instead of **true**. Is this really supposed to happen or is it a real bug?

**Comment by pointfeev** [comment]
Yes of course it's intended... if you disable a DLC you obviously don't want to unlock all of them?

**Comment by Com3Carne** [comment]
> Yes of course it's intended... if you disable a DLC you obviously don't want to unlock all of them?

But I'm disabling a specific DLC, not all.

**Comment by pointfeev** [comment]
The "unlock_all" option in SmokeAPI automatically unlocks all DLC possible regardless of the given app ids, thus if it's not ticked to false then that specific DLC you ticked off would still unlock. If you're curious, the purpose of providing app ids is as explained [here](https://github.com/acidicoala/SmokeAPI#:~:text=%5B%5D-,dlc_ids,-When%20game%20requests).

**Comment by pointfeev** [comment]
Are you having issues with the unlocking of DLCs with how it's currently set up? I very well may have misinterpreted the descriptions of the JSON parameters.

**Comment by pointfeev** [comment]
Alright I've done some more testing with the case of unticking specific DLCs, and I've fixed a bunch of shit related to it. I'll have it pushed out as v3.5.1.0 soon, please do tell if it doesn't fix your issues. :)

**Comment by Com3Carne** [comment]
First of all, I want to say that the tool is great. Coming back to the subject, I think maybe the bug is from the **SmokAPI**. I was unchecking 1 DLC from **RE2R**, which would be the soundtrack DLC. It puts it as **"unlock_all": false**, and when opening the game, they just don't release anything. I had to edit it manually, changing it from false to true and the DLCs would work again.

**Comment by pointfeev** [comment]
I'd actually misinterpreted the parameters of SmokeAPI's configuration; I reworked it in v3.5.1.0, does that not fix it?

**Comment by Com3Carne** [comment]
It's working perfectly. Thanks :)
