### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by ArtanisInc** [pointfeev/CreamInstaller#31]
The update function does not work. It's stuck at 0%
![image](https://user-images.githubusercontent.com/20884381/173184854-a0ccec61-f03d-46a3-b56a-20eea19cacb9.png)

**Comment by pointfeev** [comment]
This could simply be due to internet issues; have you tried cancelling and clicking the update button again, or trying again later when any website rate limit may wear off?

**Comment by ArtanisInc** [comment]
I don't think it's an internet problem. I tried cancelling and clicking the update button, but nothing changed. I've had this problem for 5-6 months now.

**Comment by pointfeev** [comment]
That's very odd, I'll see about sending you a debug version that could provide some more information on the matter later. Sorry for the inconvenience! You can course just download the update from GitHub manually for now. :)

**Comment by pointfeev** [comment]
Alright I've created a debug version for you [here](https://www.dropbox.com/s/ungv4nxk7rtqe4w/CreamInstaller.exe?dl=0). Please run that and see what exception(s) it gives you.

**Comment by expirius** [comment]
> Alright I've created a debug version for you [here](https://www.dropbox.com/s/ungv4nxk7rtqe4w/CreamInstaller.exe?dl=1). Please run that and see what exception(s) it gives you.

I have updated with this version.

**Comment by pointfeev** [comment]
It's been over a month. Please provide some feedback or I'm going to close the issue in a week or two. :)

**Comment by ArtanisInc** [comment]
The debug version doesn't output anything, but I manage to apply the update, I just let the program running and that's it. The problem is that the progress bar does not work.

**Comment by pointfeev** [comment]
Yes the progress bar doesn't really do much before it simply restarts the program. This is an Onova thing, nothing I can do about it.

**Comment by Hlebuw3k** [comment]
This issue still occurs. When I moved the executable to a different drive in a root directory, it managed to update itself. I believe it is caused by non-english characters being present in the folder name.

**Comment by pointfeev** [comment]
> This issue still occurs. When I moved the executable to a different drive in a root directory, it managed to update itself. I believe it is caused by non-english characters being present in the folder name.

That sounds plausible, I'll do some tests and see if I can fix that if so. 😀

**Comment by pointfeev** [comment]
> This issue still occurs. When I moved the executable to a different drive in a root directory, it managed to update itself. I believe it is caused by non-english characters being present in the folder name.

This was in fact the issue. It should be fixed in the next update.
