### ISSUE TITLE
Paradox Launcher Unable to locate configuration file

### ISSUE THREAD

**Issue by Limyx826** [pointfeev/CreamInstaller#33]
Paradox Launcher will kept showing "Unable to locate configuration file". Not sure it is on SmokeAPI or the paradox launcher fixing.

**Comment by pointfeev** [comment]
This is a common occurrence upon launcher updates. Use the context menu "Repair" option or run the program with the launcher and Paradox games selected again.

**Comment by Limyx826** [comment]
Now if tried to repair from context menu this happens
![image](https://user-images.githubusercontent.com/38696851/174107951-d92aea8e-0810-43a6-a014-9f0f60ff7c10.png)

**Comment by pointfeev** [comment]
Ah, I'll look into that. Reinstall as normal, that should work fine.

**Comment by pointfeev** [comment]
You likely have an earlier version of SmokeAPI installed to the Paradox Launcher from earlier versions of the program. The program currently can't take older DLL versions into account, and thus can't "repair" (swap them around) correctly.

You can go to releases and try repairing with older versions (you can see when the SmokeAPI versions were updated in the change logs).

I'll see if there's any way I can have it detect these older versions sometime.

**Comment by Limyx826** [comment]
Actually in my case is that I updated from CreamAPI to SmokeAPI. I hadn't check with CreamInstaller for a month now so I had no idea about the change with the update.

**Comment by Limyx826** [comment]
I just fixed my problem by reinstall the paradox launcher and generate with latest version of CreamAPI. 

Sidenote: Can you add a feature to remember which DLCs to exclude in the future? Cause games like Paradox games have tons of DLCs and to exclude some of them is a bit tedious when install new version.

**Comment by pointfeev** [comment]
That's definitely a possibility, I'll create a new issue for it so I don't forget. :)

**Comment by pointfeev** [comment]
The repairing exception and issues related to old CreamAPI/SmokeAPI versions should be resolved in v3.5.3.0! :)
