### ISSUE TITLE
Arma 3 Infinite "Initializing mods management"

### ISSUE THREAD

**Issue by xavieraiden** [pointfeev/CreamInstaller#35]
When using CreamInstaller with Arma 3, I've noticed that (as far as I'm aware) will infinitely load the mods
![image](https://user-images.githubusercontent.com/45552520/175123576-ad91a951-32c4-4790-9207-970094857cd9.png)
No configuration of enabled DLC's has seemed to work for me so I'm guessing it has to do with creamapi itself

**Comment by pointfeev** [comment]
This is a SmokeAPI issue, report it [here](https://cs.rin.ru/forum/viewtopic.php?f=29&t=122487).

**Comment by xavieraiden** [comment]
Will do

**Comment by pointfeev** [comment]
After conferring on cs.rin.ru, I'll have an exception for Arma 3's launcher added in the next version, so this will no longer be an issue. :)

**Comment by pointfeev** [comment]
After conferring on cs.rin.ru with Christsnatcher, I've fixed this issue in v3.5.4.0! :)
