### ISSUE TITLE
Does Creaminstaller work with any ubisoft games?

### ISSUE THREAD

**Issue by Ferixy** [pointfeev/CreamInstaller#39]
hi, i want to know if this project works with Ubisoft games like watchdogs 2 and rainbow six siege?
thank you! , have a nice day.

**Comment by pointfeev** [comment]
not currently, and siege is an online game anyhow; you should not expect that to work

**Comment by pointfeev** [comment]
Note that as of v3.6.0.0, Uplay R1 and Uplay R2 unlockers were added, so it may work with certain Ubisoft Connect games now.

**Comment by peter9811** [comment]
> Note that as of v3.6.0.0, Uplay R1 and Uplay R2 unlockers were added, so it may work with certain Ubisoft Connect games now.

Sorry, for reply to and old issue. I have a coupe of games (legits ones) on Ubisoft Connect, but even installed, CreamInstaller is not recognizing those
I have a whole external drive with the games installed. Steam and EA is working, but Ubisoft no,
Maybe have to stay on C drive or...?
