### ISSUE TITLE
Exception when Gathering

### ISSUE THREAD

**Issue by kgamecarter** [pointfeev/CreamInstaller#4]
https://github.com/pointfeev/CreamInstaller/blob/ffbbeedeffdaca33f0cf336c1ab458408c054f3c/CreamInstaller/Classes/SteamCMD.cs#L147

![image](https://user-images.githubusercontent.com/3646532/150734527-0dfdd28a-d646-4e10-98ec-beb8848f73f7.png)

![image](https://user-images.githubusercontent.com/3646532/150736258-22d5a8f1-464e-4d03-9b40-d421b6bd7a42.png)

**Comment by pointfeev** [comment]
Should be fixed in v2.2.4.1! If not, please tell me! :)

**Comment by kgamecarter** [comment]
thx. Fixed
