### ISSUE TITLE
Windows Defender on 11 22H2 detects Koaloader as a trojan.

### ISSUE THREAD

**Issue by DabiaTheNord** [pointfeev/CreamInstaller#42]
On Windows 11, build 22H2 and potentially other builds (untested) detect all outputted files including Koaloader as the virus `Trojan:Script/Phonzy.a!ml`, which is a very unusual virus that steals banking information.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572
