### ISSUE TITLE
Paradox Launcher not working with CreamInstaller

### ISSUE THREAD

**Issue by AqueousDog** [pointfeev/CreamInstaller#43]
###### Describe the bug and/or provide an image of the exception dialog box:
Version v4.1.2.0

I cannot seem to find the Paradox Launcher when selecting games, and I've looked through the list several times now. I have EU4, Cities: Skylines, Stellaris, HOI4, Imperator: Rome, and CK3 selected (and Vic2 but that doesn't use the PDX launcher). After selecting Generate and Install I read the log which does not mention the Paradox Launcher. I am trying to play EU4 and it gives me the "Unable to locate the configuration file" error. Right-clicking to open the context menu for any of these games does not mention repairing the launcher. I'm not sure if it's supposed to or if that's for if the launcher is a selected program, but as mentioned before I can't select it.
My launcher directory is the normal "C:\Users\[user]\AppData\Local\Programs\Paradox Interactive"

**Comment by AqueousDog** [comment]
Installation log:

Installing Koaloader to Victoria II in directory "C:\Games\Steam\steamapps\common\Victoria 2" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Installing Koaloader to Victoria II in directory "C:\Games\Steam\steamapps\common\Victoria 2\movies" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Operation succeeded for Victoria II.
Installing Koaloader to Imperator: Rome in directory "C:\Games\Steam\steamapps\common\ImperatorRome\binaries" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Installing Koaloader to Imperator: Rome in directory "C:\Games\Steam\steamapps\common\ImperatorRome\launcher" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Operation succeeded for Imperator: Rome.
Installing Koaloader to Crusader Kings III in directory "C:\Games\Steam\steamapps\common\Crusader Kings III\binaries" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Installing Koaloader to Crusader Kings III in directory "C:\Games\Steam\steamapps\common\Crusader Kings III\launcher" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Operation succeeded for Crusader Kings III.
Installing Koaloader to Europa Universalis IV in directory "C:\Games\Steam\steamapps\common\Europa Universalis IV" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Europa Universalis IV in directory "C:\Games\Steam\steamapps\common\Europa Universalis IV" . . . 
Added override DLC to SmokeAPI.json with appid 528600 (Unknown)
Added override DLC to SmokeAPI.json with appid 1109150 (Unknown)
Added override DLC to SmokeAPI.json with appid 1173840 (Unknown)
Added inject DLC to SmokeAPI.json with appid 241360 (Europa Universalis IV: 100 Years War Unit Pack)
Added inject DLC to SmokeAPI.json with appid 241361 (Europa Universalis IV: Horsemen of the Crescent Unit Pack)
Added inject DLC to SmokeAPI.json with appid 241362 (Europa Universalis IV: Winged Hussars Unit Pack)
Added inject DLC to SmokeAPI.json with appid 241363 (Europa Universalis IV: Star and Crescent DLC)
Added inject DLC to SmokeAPI.json with appid 241365 (Europa Universalis IV: Purple Phoenix)
Added inject DLC to SmokeAPI.json with appid 241366 (Europa Universalis IV: National Monuments)
Added inject DLC to SmokeAPI.json with appid 241367 (Europa Universalis IV: Conquest of Constantinople Music Pack)
Added inject DLC to SmokeAPI.json with appid 414300 (Europa Universalis IV: Catholic Majors Unit Pack)
Added inject DLC to SmokeAPI.json with appid 472030 (Europa Universalis IV: Fredman's Epistles)
Added inject DLC to SmokeAPI.json with appid 960850 (Europa Universalis IV: Test 6)
Added inject DLC to SmokeAPI.json with appid 1009630 (Europa Universalis IV: Imperator Unit Pack)
Operation succeeded for Europa Universalis IV.
Installing Koaloader to Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines" . . . 
Added override DLC to SmokeAPI.json with appid 346790 (Unknown)
Installing Koaloader to Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\bin" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Generating SmokeAPI configuration for Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\bin" . . . 
Added override DLC to SmokeAPI.json with appid 346790 (Unknown)
Installing Koaloader to Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\2.0" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Generating SmokeAPI configuration for Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\2.0" . . . 
Added override DLC to SmokeAPI.json with appid 346790 (Unknown)
Installing Koaloader to Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\unity" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Generating SmokeAPI configuration for Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\unity" . . . 
Added override DLC to SmokeAPI.json with appid 346790 (Unknown)
Installing Koaloader to Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\unity_web" . . . 
Wrote 32-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI32.dll
Generating SmokeAPI configuration for Cities: Skylines in directory "C:\Games\Steam\steamapps\common\Cities_Skylines\Mono\lib\mono\unity_web" . . . 
Added override DLC to SmokeAPI.json with appid 346790 (Unknown)
Operation succeeded for Cities: Skylines.
Installing Koaloader to Stellaris in directory "C:\Games\Steam\steamapps\common\Stellaris" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Stellaris in directory "C:\Games\Steam\steamapps\common\Stellaris" . . . 
Added override DLC to SmokeAPI.json with appid 447688 (Unknown)
Added override DLC to SmokeAPI.json with appid 447750 (Unknown)
Installing Koaloader to Stellaris in directory "C:\Games\Steam\steamapps\common\Stellaris\pdx_browser" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Stellaris in directory "C:\Games\Steam\steamapps\common\Stellaris\pdx_browser" . . . 
Added override DLC to SmokeAPI.json with appid 447688 (Unknown)
Added override DLC to SmokeAPI.json with appid 447750 (Unknown)
Operation succeeded for Stellaris.
Installing Koaloader to Hearts of Iron IV in directory "C:\Games\Steam\steamapps\common\Hearts of Iron IV" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Hearts of Iron IV in directory "C:\Games\Steam\steamapps\common\Hearts of Iron IV" . . . 
Added override DLC to SmokeAPI.json with appid 460552 (Unknown)
Added override DLC to SmokeAPI.json with appid 471560 (Unknown)
Added override DLC to SmokeAPI.json with appid 472411 (Unknown)
Added override DLC to SmokeAPI.json with appid 486950 (Unknown)
Added override DLC to SmokeAPI.json with appid 1880660 (Unknown)
Installing Koaloader to Hearts of Iron IV in directory "C:\Games\Steam\steamapps\common\Hearts of Iron IV\pdx_browser" . . . 
Wrote 64-bit Koaloader: version.dll
Wrote SmokeAPI: SmokeAPI64.dll
Generating SmokeAPI configuration for Hearts of Iron IV in directory "C:\Games\Steam\steamapps\common\Hearts of Iron IV\pdx_browser" . . . 
Added override DLC to SmokeAPI.json with appid 460552 (Unknown)
Added override DLC to SmokeAPI.json with appid 471560 (Unknown)
Added override DLC to SmokeAPI.json with appid 472411 (Unknown)
Added override DLC to SmokeAPI.json with appid 486950 (Unknown)
Added override DLC to SmokeAPI.json with appid 1880660 (Unknown)
Operation succeeded for Hearts of Iron IV.
DLC unlocker(s) successfully installed and generated for 7 program(s).

**Comment by pointfeev** [comment]
You have to actually select the Paradox Launcher to be scanned and in the selection form; if the program can't find it then it may be bugged up, you might wanna reinstall it.

**Comment by AqueousDog** [comment]
Thank you, reinstalling the launcher fixed it. It seems that it was absent from my Programs and Features list before reinstalling, which probably had something to do with it.
