### ISSUE TITLE
I tried installing DLCS for "Total War : Warhammer 2" and "Stellaris". It worked fine before, but now the dlcs simply aint there. 

### ISSUE THREAD

**Issue by tatahi5534** [pointfeev/CreamInstaller#44]
I tried installing DLCS for "Total War : Warhammer 2" and "Stellaris". It worked fine before, but now the dlcs simply aint there.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller#note-this-program-does-not-automatically-download-nor-install-actual-dlc-files-for-you-as-the-title-of-the-program-says-its-only-a-dlc-unlocker-installer-should-the-game-you-wish-to-unlock-dlc-for-not-already-come-with-the-dlcs-installed-very-many-do-not-you-have-to-find-download-and-install-those-yourself-preferably-you-should-be-referring-to-the-proper-csrinru-post-for-the-games-youre-tinkering-with-youll-usually-find-any-answer-to-your-problems-there
