### ISSUE TITLE
Cannot open the Installer

### ISSUE THREAD

**Issue by nicolas898** [pointfeev/CreamInstaller#45]
Basically I click in the "CreamInstaller" file and it does nothing, cannot even find a hidden folder on my PC or anything alike.

**Comment by pointfeev** [comment]
You can try installing [.NET Desktop Runtime 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.9-windows-x64-installer). If that doesn't fix it, then it's likely an issue with your operating system in some way; there's no reason you shouldn't be able to launch a simple WinForms application. Look into repairing your Windows installation and your drivers.

**Comment by nicolas898** [comment]
It worked after installing that Windows file. Thanks!
