### ISSUE TITLE
Hello, i have a quick question!

### ISSUE THREAD

**Issue by LoleczekgREZ** [pointfeev/CreamInstaller#48]
So I've been using your program for some time now, and I've noticed that for some reason my Windows Defender detects a "virus" when trying to use your program on specific games.  It happend when i used your program on a game called "Planet Zoo" but i turned off my antivirus and yes, the dlcs were working. But can it be dangerous? 

Keep in mind that i am far from Expert in these type  of things so i dont know why it happens.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572

No problem at all to be worried, you should be! Personally, I had to do research as well after seeing everything it was detected as (Phonzy sure sounds scary); Defender is really ass at detection with Koaloader's DLLs it appears, it detects it as something different every day, and I'm constantly having to tell it to shut up; it is what it is, nothing can be done about it.
