### ISSUE TITLE
DLCs not working at all

### ISSUE THREAD

**Issue by Capybaron** [pointfeev/CreamInstaller#51]
I have tried CreamInstaller on two games, specifically Goat Simulator and Prison Architect. Neither have unfortunately worked. All of the DLCs were checked in the program aswell. Any ideas here?

EDIT: I have made Prison Architect work by disabling Koalaloader

**Comment by pointfeev** [comment]
"Preferably, you should be referring to the proper cs.rin.ru post for the game(s) you're tinkering with; you'll usually find any answer to your problems there."
