### ISSUE TITLE
Shows duplicate entry for Tiny Tina's Wonderlands (Epic)

### ISSUE THREAD

**Issue by xADDBx** [pointfeev/CreamInstaller#52]
Title describes it; 
![grafik](https://user-images.githubusercontent.com/62178123/202918315-939bc6d3-c827-4071-afcf-da917391f93a.png)
If you need any further details just ask.

**Comment by pointfeev** [comment]
Do they point to separate directories? Use the right click context menu.

**Comment by pointfeev** [comment]
Should be fixed in v4.2.3.1!
