### ISSUE TITLE
Having problem with windows 11 22H2 

### ISSUE THREAD

**Issue by VermillionH** [pointfeev/CreamInstaller#54]
just trying to use it for first time and this error happened
![Screenshot_20221125_102156](https://user-images.githubusercontent.com/119064485/204016783-a54609f6-ccc4-4eff-b946-69beca78fc62.png)

**Comment by pointfeev** [comment]
Try the steps I mentioned [here](https://github.com/pointfeev/CreamInstaller/issues/45#issuecomment-1267717775) perhaps, otherwise this exception doesn't really make much sense.

**Comment by pointfeev** [comment]
This will likely be fixed in v4.3.0.0 with string culture fixes, and I'm going to go ahead and close this issue since there's been no response.
