### ISSUE TITLE
City Skylines will not launch with DLC(s)

### ISSUE THREAD

**Issue by Jaddub-commits** [pointfeev/CreamInstaller#55]
Have tried reinstalling city skylines, and verifying game files without success. The game repairs itself without DLC after the first launch

Photo of error:
![image](https://user-images.githubusercontent.com/80666883/204173109-b54d019c-30ff-4c58-abbc-86ddf1df7136.png)

**Comment by pointfeev** [comment]
https://cs.rin.ru/forum/viewtopic.php?f=10&t=65297
