### ISSUE TITLE
Trojan:Script/Phonzy.A1ML

### ISSUE THREAD

**Issue by w-m0nty** [pointfeev/CreamInstaller#56]
I installed and my windows defender is claiming to have found a trojan virus.

![image](https://user-images.githubusercontent.com/119473347/204707709-a0c5d74e-f3fd-4117-9912-6e06971f798c.png)

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572

**Comment by McraftYT** [comment]
Hello, this tests that this is not virus, but how to actually install it? My computer immediately deletes files when I install it.

**Comment by McraftYT** [comment]
How to make windows not automatically remove the zip file?
