### ISSUE TITLE
Installer installs Trojan:BAT/Malagent!MSR while unlocking Pillars of Eternity II DLC's.

### ISSUE THREAD

**Issue by canercetin-randomguy** [pointfeev/CreamInstaller#57]
###### Describe the bug and/or provide an image of the exception dialog box:

Hey. I didn't expect such a problem while using your software, I used it many times until now, but the installer just installed a virus while unlocking PoE II DLC. The game didn't launch, Windows Defender blocked it, but yet still. Can you look into it?

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:BAT/Malagent!MSR&threatId=-2147146986

Virus was located at version.dll.

![image](https://user-images.githubusercontent.com/92731060/205512492-de917c27-9d49-4a3e-a6aa-976603eda99e.png)

**Comment by canercetin-randomguy** [comment]
Never mind. https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572

**Comment by pointfeev** [comment]
You'd have to ask Windows why, I'm not a cyber security expert. Defender will mark it as anything from Phonzy.A, Phonzy.B, to now recently Malgent on my system personally.

**Comment by canercetin-randomguy** [comment]
Lmao, thank you a lot mate. Thanks again for the project.
