### ISSUE TITLE
Windows Defender flag v4.3.0.1 as malicious

### ISSUE THREAD

**Issue by Limyx826** [pointfeev/CreamInstaller#61]
As the title said. 
![image](https://user-images.githubusercontent.com/38696851/209182891-1b4a041a-a2a9-463e-a8c6-6ae858fde219.png)

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572

**Comment by Limyx826** [comment]
Funny so it is Koaloader problem then?

**Comment by pointfeev** [comment]
If anything, I'd say it's a Windows Defender problem. Virus detections can be quite strange at times regardless of what you do. There was a point where this very app was called a virus due to some code that called a website to get favicons; not sure if that's still a thing or not.

**Comment by Limyx826** [comment]
On an unrelated note, when I am updating the progress bar does nothing, but it is updating in the background successfully. So, could you check on it?

**Comment by pointfeev** [comment]
Not really anything I can do about that, that's an [Onova](https://github.com/Tyrrrz/Onova) issue.
