### ISSUE TITLE
4.3.0.1 doesn't open

### ISSUE THREAD

**Issue by DillPickle31** [pointfeev/CreamInstaller#63]
I installed 4.3.0.1 and it didn't open, so I installed 4.3.0.0 and it worked but as soon as I clicked the update button it closed and refused to open afterwards

**Comment by pointfeev** [comment]
Download [.NET 7 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.1-windows-x64-installer).

**Comment by Samh629** [comment]
Hello,   i downloaded the newest one from 3 days ago on the github now it wont start at all.   my pc trys and opens  Windows problem reporting.   i have added a file of my specs and windows version 
[Computer specs 2022 Dec.txt](https://github.com/pointfeev/CreamInstaller/files/10298741/Computer.specs.2022.Dec.txt)
Here is a video of what happens in task manager as this is the only place it shows it opens. : https://sam-h.scot/Desktop%202022.12.24%20-%2014.25.49.01.mp4

Thanks in advance

**Comment by Samh629** [comment]
after having a think i thought it could be windows defender stopping it and i was correct it was blocking it all u need to do is unblock it and it should run i got mine too
