### ISSUE TITLE
Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by nskserega** [pointfeev/CreamInstaller#64]
###### Describe the bug and/or provide an image of the exception dialog box:
When trying to install CreamInstaller.exe antivirus detects Trojan:Win32/Wacatac.H!ml

<a href="https://imgbb.com/"><img src="https://i.ibb.co/9VgSrxN/2022-12-25-193518.jpg" alt="2022-12-25-193518" border="0"></a>
Why is there a trojan?

**Comment by unicornturtle** [comment]
I have a similar issue, Windows Security detected: "Trojan:Script/Phonzy.A!ml" after I ran autocreamapi on the game Battle Brothers.

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/40#issuecomment-1228050572
