### ISSUE TITLE
Cream doesnt install/unlock for Stellaris 3.6+

### ISSUE THREAD

**Issue by Vralr** [pointfeev/CreamInstaller#65]
Hello dear developers of CreamApi,
I get straight down to the point. I get all dlcs for Stellaris, did a clean install both the launcher and the game itself and it doesnt activate, unlock or anything. Im quite new to this here, so if you need any information that I missed, tell me. May I am just stupid and didnt do it right - but I assume I just had to install for launcher and Stellaris? 

Yours sincerely Vralr

**Comment by pointfeev** [comment]
Yes, you just need to install for the launcher and whatever other Paradox games you want. Make sure you install the actual DLC files themselves to the game's directory as well; refer to around [here](https://cs.rin.ru/forum/viewtopic.php?f=10&t=68551&start=6975) to find those.

**Comment by Vralr** [comment]
Hello again!
Yes it worked just fine - confused though, because the only thing I did differently, putting "more recent" dlcs in the folder. I already had toxoids+ and that wouldnt work. But the ones from your link did? I'm curious about it, but no answer needed, anyway thank you for quick response. Have a great day and happy new year.

-- Vralr
