### ISSUE TITLE
No DLC after restarting the  game

### ISSUE THREAD

**Issue by GuacamoleGH** [pointfeev/CreamInstaller#66]
###### Describe the bug and/or provide an image of the exception dialog box:
After unlocking all DLC on Assetto Corsa Competizione and restarting the game, all DLC are locked and I have to unlock them.
Any solution?

**Comment by pointfeev** [comment]
Try looking or asking around [here](https://cs.rin.ru/forum/viewtopic.php?f=10&t=88060).
