### ISSUE TITLE
CreamInstaller encountered a fatal exception

### ISSUE THREAD

**Issue by azraelender** [pointfeev/CreamInstaller#67]
![Sem título](https://user-images.githubusercontent.com/106407782/212420570-1da007d4-8522-4f8c-b9bb-a0999c9241c1.jpg)

**Comment by NTcompanyYT** [comment]
yeah i got the **same** Error.

**Comment by pointfeev** [comment]
Should be fixed in [v4.4.0.1](https://github.com/pointfeev/CreamInstaller/releases/tag/v4.4.0.1), sorry! :)
