### ISSUE TITLE
installer not working on win7?

### ISSUE THREAD

**Issue by MatrixFr** [pointfeev/CreamInstaller#68]
Hello,

I try DL and install your program, but nothing happen when I execute .exe

I try install .NET 7 Runtime like specified but nothing change (after reboot too)

I'm on win7, any idea ?

thx

**Comment by pointfeev** [comment]
not sure, you must have something wrong with your OS or you're not waiting long enough; I'd really recommend updating to AT LEAST windows 10, and if not then you should look into repairing 7
