### ISSUE TITLE
stuck at scanning

### ISSUE THREAD

**Issue by khanhvietmine** [pointfeev/CreamInstaller#69]
###### Describe the bug and/or provide an image of the exception dialog box:
![image_2023-01-25_093423299](https://user-images.githubusercontent.com/34242857/214467865-dd49a275-3078-474c-ba3e-d8ec08bec4b7.png)

**Comment by pointfeev** [comment]
Should be fixed in v4.6.0.0!

**Comment by happyTonakai** [comment]
I thought I also had this issue but after a long wait (about 5 minutes) it moved forward!
