### ISSUE TITLE
Game Scanning Stuck (SteamCMD issue)

### ISSUE THREAD

**Issue by Eu9eney** [pointfeev/CreamInstaller#7]
###### Describe the bug and/or provide an image of the exception dialog box:
Scanning of games and their DLC does not go beyond 9%, tried versions 2.3.0.0 and 2.3.1.0
I use Windows 11
![image](https://user-images.githubusercontent.com/99332197/153196236-fa3deb6d-85d5-4f70-8216-fa3cf5fcdd96.png)

**Comment by CuPidev** [comment]
Probably your problem, I have no problems (downloaded 30 minutes ago)

**Comment by pointfeev** [comment]
Did this issue occur in 2.2.0.0? Before the "Remaining games/DLCs" update 2.3.0.0? If not, that would really help narrow down the issue.

**Comment by pointfeev** [comment]
Assuming this issue also occurred in v2.2.4.4, I released v2.3.1.1 with some tiny tweaks to task handling that MAY fix your issue. If not then it's going to be SteamCMD-related, which may be more difficult to fix. Please tell me if **a. it also occurs in v2.2.4.4** and **b. whether or not v2.3.1.1 fixed it at all**. :)

**Comment by Eu9eney** [comment]
On 2.2.4.4, the search for games stops at 8%, and does not go further
![image](https://user-images.githubusercontent.com/99332197/153337339-bd8cd5d5-7a39-405a-a5c6-2a387095139a.png)
Paradox launcher appears and everything stops

**Comment by pointfeev** [comment]
Hmmm, well from the v2.3.1.0 picture you took, the program clearly is gathering your game directories correctly otherwise no games would be showing up in "Games remaining." Therefore, it would have to be some sort of issue with SteamCMD. I'll see if I can figure out how to fix that problem. :)

Meanwhile, you could try deleting the app data folder **%AppData%\CreamInstaller** and running it again to see if that solves it, as perhaps your SteamCMD install could be broken for some odd reason.

**Comment by pointfeev** [comment]
Actually, I've just found out something. 
![image](https://user-images.githubusercontent.com/15071274/153436341-2afacd17-ddd6-4546-80b1-fb2c22e61c92.png)
That is what it should look like when gathering appinfo for games.

Mine only says "Steam Client Bootstrapper" when downloading/installing SteamCMD:
![image](https://user-images.githubusercontent.com/15071274/153436661-1edf7c1f-2d87-416b-942a-6e4a772e15a7.png)

So it very well could be your antivirus stopping SteamCMD.

**Comment by Eu9eney** [comment]
Disabled antivirus does not solve the problem

**Comment by pointfeev** [comment]
I'll have to further analyze my SteamCMD code to figure out why it's getting stuck then.

**Comment by Eu9eney** [comment]
is there any log file that I could send you to simplify the analysis?

**Comment by pointfeev** [comment]
I can quickly send you a little debug version with uncommented code I had used before, which would spit out the type of issue and a bit of the SteamCMD output. It's very debuggy in the sense that it's not very polished, and a shit ton of windows pop up from it lmao. I'll attach it, feel free to open it up and send pictures of a couple of the dialog boxes that show up from it.

**Comment by pointfeev** [comment]
https://www.dropbox.com/s/upisjxk6dcyadsw/CreamInstaller.zip?dl=1

**Comment by Eu9eney** [comment]
![image](https://user-images.githubusercontent.com/99332197/153702861-a3ad9244-53c3-4139-9ef7-1952d7a1b975.png)
![image](https://user-images.githubusercontent.com/99332197/153702863-69785cc6-c074-4656-b480-3732d1c537e8.png)
I seem to understand what the problem is, my username is written in Cyrillic, and the path contains non-English characters.

**Comment by pointfeev** [comment]
Hmm, everything in my program was converted to UTF-8 a while back, so if that's the issue then it's solely SteamCMD itself, nothing I can even do about it. The only thing I could think of that I personally could do with the program to help you is find another location to store data, but I'm not sure of any. I'll see if I can find someplace perhaps.

**Comment by pointfeev** [comment]
Actually, I can use "C:\ProgramData", that would easily fix your issue.

**Comment by pointfeev** [comment]
I'm setting up v2.3.3.1 to move the old data folder to the new one so it doesn't disrupt old data for no reason. I'll tell you when the update is ready. :)

**Comment by pointfeev** [comment]
Alright v2.3.3.1 should fix it for you, feel free to close the issue if so! :)

**Comment by Eu9eney** [comment]
![image](https://user-images.githubusercontent.com/99332197/153704278-4a5e308e-8585-4b5c-aaca-0f4789a9b59e.png)
Thanks it works
