### ISSUE TITLE
CreamInstaller encountered a fatal exception

### ISSUE THREAD

**Issue by Regular-Bagel** [pointfeev/CreamInstaller#70]
###### Describe the bug and/or provide an image of the exception dialog box:
Keep getting this error when I try to boot the .exe
![image](https://user-images.githubusercontent.com/123776243/215198733-a6014778-6a30-41e8-b618-3c0417fab4ea.png)

**Comment by pointfeev** [comment]
Will be fixed in upcoming v4.6.0.0!
