### ISSUE TITLE
Doesn't work for Europa universalis 4

### ISSUE THREAD

**Issue by JonnyJalapeno** [pointfeev/CreamInstaller#74]
The game launcher still says it can't verify ownership of dlc.

**Comment by pointfeev** [comment]
Then tweak your installation settings; I noticed personally that Koaloader no longer works on the Paradox Launcher.

**Comment by JonnyJalapeno** [comment]
How to unlock lions of the north/scandinavian unit pack? It just won't no matter what i do.

**Comment by pointfeev** [comment]
download the DLC
