### ISSUE TITLE
 cannot detect cities skylines

### ISSUE THREAD

**Issue by leonfueguno** [pointfeev/CreamInstaller#75]
it should be noted that it is not original

**Comment by leonfueguno** [comment]
What do I need to do for it to detect it?

**Comment by pointfeev** [comment]
What do you mean it can't detect? Do you mean this program isn't finding it installed on your computer or that DLC aren't unlocking?

**Comment by leonfueguno** [comment]
that the pc does not detect the installed game but I do have it there

**Comment by leonfueguno** [comment]
I don't know if it has to do with the fact that the game is not from Steam and that it is hacked

**Comment by pointfeev** [comment]
My friend this is a DLC Unlocker, it's only for legitimately owned games; game cracks should include unlocking DLCs....
