### ISSUE TITLE
Do I need to re-run this script everytime a game updates in Steam?

### ISSUE THREAD

**Issue by halpz** [pointfeev/CreamInstaller#76]
I'm not sure if I could find this information anywhere, maybe it would be useful to put on the readme.

I;m not sure whether I should be re-running this script after steam downloads an update for the game

**Comment by pointfeev** [comment]
The general rule is such that whenever this program is updated, or a game where you've installed without Koaloader is updated or verified, you should reinstall. Realistically, Steam may do things itself, so you just have to run the game and see if it still works or just run the program real fast before playing, entirely up to you.
