### ISSUE TITLE
Whats going on here exactly

### ISSUE THREAD

**Issue by Luthier2** [pointfeev/CreamInstaller#79]
![image](https://user-images.githubusercontent.com/120297408/222975411-e228e5f8-4058-4e48-84f2-5c4b557288b5.png)
I get this popup every time i launch the game.

**Comment by Luthier2** [comment]
And uninstalling fixes this issue fixes this popup and will let me enter the game

**Comment by Luthier2** [comment]
the dlc i mean

**Comment by pointfeev** [comment]
https://cs.rin.ru/forum/viewtopic.php?f=10&t=72155&p=2741421
