### ISSUE TITLE
select only certain dlcs?

### ISSUE THREAD

**Issue by guacamolenjoyer** [pointfeev/CreamInstaller#80]
###### Describe the new feature and its implementation OR how the existing feature could be improved:
cities skylines crashes a lot and with LSM it tells me that it happens when it loads the dlc. if you could add a way to only select the dlc you want it would make it a lot easier and less time consuming (so i dont have to disable more than half of my assets 😬)

**Comment by pointfeev** [comment]
You can already do this...

**Comment by guacamolenjoyer** [comment]
> You can already do this...

how? ive looked but cant find it, and it wasnt in any faq

**Comment by guacamolenjoyer** [comment]
i tried uninstalling and reinstalling but i dont see an option

**Comment by pointfeev** [comment]
Click the + to the left of game names and unselect what you don't want.
