### ISSUE TITLE
Ability to load a prior dlc configuration

### ISSUE THREAD

**Issue by xADDBx** [pointfeev/CreamInstaller#81]
Case: A game that has quite a few DLCs just got another one which I wanted to unlock. For various reasons, I don't want to unlock every DLC, and instead only pick a few. Every time I want to add another one (like on this occasion) I need to manually reselect the ones I want (or deselect the ones I don't want) which can be a bit of a bother with games that have a lot of DLCs. Would it be possible to add the option to load from an existing configuration and then just modify that?

**Comment by pointfeev** [comment]
There are save and load DLC buttons already, do they not work how you want?

**Comment by pointfeev** [comment]
I might consider using an existing configuration, we'll see. :)
