### ISSUE TITLE
Error: Game is already running when there is no game running

### ISSUE THREAD

**Issue by choconinja** [pointfeev/CreamInstaller#82]
Self explanatory. Here's a screencap of the error. No processes or executables related to the game were launched.
![image](https://user-images.githubusercontent.com/37037129/224521067-c3c35933-b34c-4069-a7b1-f494cadc2b90.png)

**Comment by pointfeev** [comment]
This just means that something on your computer is using and therefore locking the DLLs of the game, meaning the program can't do anything to them. This can be from an antivirus or the game running most commonly, or many other things. I should rephrase the alert but otherwise it's not a bug.
