### ISSUE TITLE
Updating SmokeAPI doesn't show download progress

### ISSUE THREAD

**Issue by Melyyn** [pointfeev/CreamInstaller#84]
I launched creaminstaller.exe today & it showed that SmokeAPI needs an update, after clicking update, the progress bar was stuck at 0%. It took about 5 minutes & then it apparently updated & then creaminstaller restarted and worked as usual. I checked task manager & creaminstaller was using network bandwidth during the update not sure why it was stuck at 0%

**Comment by pointfeev** [comment]
This is just an Onova thing, nothing I can really do about it. If it took 5 minutes then it's either your internet connection or GitHub was having issues at the time.
