### ISSUE TITLE
Does not work for Cities Skyline DLC skyline

### ISSUE THREAD

**Issue by kimzy999** [pointfeev/CreamInstaller#85]
###### Describe the bug and/or provide an image of the exception dialog box:

Getting the bug: 

 "The game appears to have crashed or terminated unexpectedly (exit code 3221225477). The issue may be solved by verifying the integrity of your game files and deactivating any mods. If you are using Windows, you may also need to install Visual C++ Redistributable and .NET Framework."
 
 When trying to launch the game 2 times, then automatically starts the game and repairs the game files and *removes* the DLC's
 
 Don't see anyone that reported this so here I am!
 
 Thank you

**Comment by pointfeev** [comment]
https://github.com/pointfeev/CreamInstaller/issues/55#issuecomment-1328445359
