### ISSUE TITLE
Unable to download on Chrome or Edge 

### ISSUE THREAD

**Issue by zishanj4** [pointfeev/CreamInstaller#90]
###### Describe the bug and/or provide an image of the exception dialog box:

Hi, i tried to download the zip file on Chrome and Edge and both times it stopped the download as it "detected a Virus".

My browser anti virus is off. is there anything else i may need switch off ? 

![Screenshot 2023-04-14 153339](https://user-images.githubusercontent.com/65806462/232074159-8d194537-34ee-44d4-917a-65aeb1e5ca61.png)

**Comment by pointfeev** [comment]
That's probably not a browser thing, and is instead Windows Defender or whatever other antivirus you have.
