### ISSUE TITLE
House Flipper

### ISSUE THREAD

**Issue by Risiek** [pointfeev/CreamInstaller#96]
It doesn't work on _House Flipper_. Please fix it.

**Comment by Risiek** [comment]
on _DCS World_ doesn't work either

**Comment by pointfeev** [comment]
#94

**Comment by Risiek** [comment]
I mean that dlc after adding in many ways, e.g. CreamInstaller, they don't load. it shows "buy"

**Comment by pointfeev** [comment]
You probably need to [download and install the DLC](https://github.com/pointfeev/CreamInstaller#note-this-program-does-not-automatically-download-nor-install-actual-dlc-files-for-you-as-the-title-of-the-program-says-its-only-a-dlc-unlocker-installer-should-the-game-you-wish-to-unlock-dlc-for-not-already-come-with-the-dlcs-installed-very-many-do-not-you-have-to-find-download-and-install-those-yourself-preferably-you-should-be-referring-to-the-proper-csrinru-post-for-the-games-youre-tinkering-with-youll-usually-find-any-answer-to-your-problems-there).

**Comment by Risiek** [comment]
yes i know. On other games it works. But on House Flipper it doesnt work

**Comment by pointfeev** [comment]
If the program does what it's supposed to, then I can't help you my friend. I'm trying to say you should refer to the cs.rin.ru post about House Flipper, they probably have it figured out there.
