### ISSUE TITLE
DLC problem , In crusader kings 3

### ISSUE THREAD

**Issue by Aspeectt** [pointfeev/CreamInstaller#97]
Need help installing DLC's in ck3 I tried every install and dll and still no luck , I tried my other games Dying light and the DLC unlocker works only in CK3 iam having a hard time, thanks

**Comment by pointfeev** [comment]
Please refer to [these](https://github.com/pointfeev/CreamInstaller#note-this-program-does-not-automatically-download-nor-install-actual-dlc-files-for-you-as-the-title-of-the-program-states-this-program-is-only-a-dlc-unlocker-installer-should-the-game-you-wish-to-unlock-dlc-for-not-already-come-with-the-dlcs-installed-as-is-the-case-with-a-good-majority-of-games-you-must-find-download-and-install-those-to-the-game-yourself) big bold messages right after installation instructions and right before usage instructions.
