### ISSUE TITLE
Maneater?

### ISSUE THREAD

**Issue by JYTheTrue** [pointfeev/CreamInstaller#99]
I tried to unlock maneater but i get this do you have tips?
![image](https://user-images.githubusercontent.com/126691531/236674567-4da1caff-1eed-4150-9fa5-b7a69a54cf2e.png)

**Comment by pointfeev** [comment]
Looks like something you'd want to report to [ScreamAPI](https://github.com/acidicoala/ScreamAPI) [here](https://cs.rin.ru/forum/viewtopic.php?p=2161197#p2161197)
